### ISSUE TITLE
RtcpReceivedEvent Rtt wrong type

### ISSUE THREAD

**Issue by chandero** [asterisk-java/asterisk-java#117]
Hi, The correct type for Rtt property must be a Double instead of Long, because some returned values from event are like '0.0368'

Thanks

sorry for my english.

**Comment by bsutton** [comment]
actually what version of asterisk-java are you using. This field was changed to a double 11 months ago.

**Comment by bsutton** [comment]
I believed this has been fixed in lastest master. So closing.
