### ISSUE TITLE
Wrong Asterisk version detected

### ISSUE THREAD

**Issue by MythTitans** [asterisk-java/asterisk-java#118]
Hi,

When I'm connecting to Asterisk 13 with asterisk-java 1.0.0-final and 1.1.0-beta, I get the message "Determined Asterisk version: Asterisk 1.6" in the log. Note that version 1.0.0-RC1 correclty prints "Determined Asterisk version: Asterisk 13".

Thanks.

**Comment by bsutton** [comment]
We have seen this issue when asterisk starts after the manager client starts.

Does that match your scenario. If so we are working on a fix.

**Comment by drencrom** [comment]
I see this same error. No matter wich service is started first. (1.1.0-beta here)

**Comment by MythTitans** [comment]
In my case, the problem was caused by the certified version of Asterisk 13 which was not matched by VERSION_PATTERN_13 in ManagerConnectionImpl.java.

Replacing the regex by `"^\\s*Asterisk (certified/)?((SVN-branch|GIT)-)?13[-. ].*"` solved the problem for me, but i did not checked yet if it would still work with all other versions.

**Comment by raarts** [comment]
This regex would not work for my version: Asterisk 13.8-cert2 built by ...

**Comment by seanbright** [comment]
Fixed by d0e47610a401fcd43dc509eca4cefe74c2c26830
