### ISSUE TITLE
DialBeginEvent Unable to set property 'accountcode'

### ISSUE THREAD

**Issue by TimofeyKuznesov** [asterisk-java/asterisk-java#124]
Asterisk 13.7.2
protocol version 'Asterisk Call Manager/2.8.0'
asterisk-java branch: master 2016.04.11

[warn] o.a.m.i.EventBuilderImpl - Unable to set property 'accountcode' to '103'
on org.asteriskjava.manager.event.DialBeginEvent: no setter.

**Comment by TimofeyKuznesov** [comment]
[warn] o.a.m.i.EventBuilderImpl - Unable to set property 'accountcode' to '103'
in
org.asteriskjava.manager.event.QueueCallerJoinEvent
org.asteriskjava.manager.event.AgentCalledEvent
org.asteriskjava.manager.event.AgentRingNoAnswerEvent
org.asteriskjava.manager.event.QueueCallerAbandonEvent
org.asteriskjava.manager.event.QueueCallerLeaveEvent

**Comment by TimofeyKuznesov** [comment]
[warn] o.a.m.i.EventBuilderImpl - Unable to set property 'accountcode' to '103'
in
org.asteriskjava.manager.event.AgentConnectEvent

**Comment by bsutton** [comment]
If you could add a setter/getter to the event and send a pull request, it would be much appreciated.
