### ISSUE TITLE
ModuleCheckResponse can lead to conversion exceptions

### ISSUE THREAD

**Issue by pk1057** [asterisk-java/asterisk-java#131]
It is not guaranteed that the module version is in integer format.

For example when you have installed the silk module from digium it will leads to error because the version number is not displayable in integer.
We could have 2 solutions for this, breaking the abi in newer version and switch the version type to string or make a new getter for a string version, changing the setter to string and fix the old getter to avoid exceptions and return a save value

**Comment by bsutton** [comment]
Can you expand the details on this.

Which module version are you talking about. Which class/method is this affecting?

**Comment by pk1057** [comment]
![screenshot_20160419_083326](https://cloud.githubusercontent.com/assets/10047641/14629805/7a6f8ee0-0609-11e6-9ad7-fdccc95f5783.png)

In the picture you can see that the codec_silk responds with the asterisk version, which can include not only numbers but also text.

--- a/src/main/java/org/asteriskjava/manager/response/ModuleCheckResponse.java
+++ b/src/main/java/org/asteriskjava/manager/response/ModuleCheckResponse.java
@@ -28,19 +28,19 @@
 {
     private static final long serialVersionUID = -7253724086340850957L;
 
-    private Integer version;
+    private String version;
 
     /**
      * Returns the version (svn revision) of the module.
      *
      * @return the version (svn revision) of the module.
      */
-    public Integer getVersion()
+    public String getVersion()
     {
         return version;
     }
 
-    public void setVersion(Integer version)
\ No newline at end of file
+    public void setVersion(String version)
\ No newline at end of file
     {
         this.version = version;
     }

**Comment by bsutton** [comment]
Push a patch. I doubt that this is going to cause much of an issue as 
its a change in a section of the code which I suspect has little use.

**Comment by bsutton** [comment]
a belated thanks.
