### ISSUE TITLE
WARNING: Unable to set property 'eventlist' to 'Complete' on

### ISSUE THREAD

**Issue by gblandz** [asterisk-java/asterisk-java#136]
WARNING: Unable to set property 'eventlist' to 'Complete' on org.asteriskjava.manager.event.StatusCompleteEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
May 05, 2016 7:49:40 PM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'listitems' to '0' on org.asteriskjava.manager.event.StatusCompleteEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
May 05, 2016 7:49:40 PM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'eventlist' to 'Complete' on org.asteriskjava.manager.event.AgentsCompleteEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
May 05, 2016 7:49:40 PM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'listitems' to '0' on org.asteriskjava.manager.event.AgentsCompleteEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
May 05, 2016 7:49:40 PM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'eventlist' to 'Complete' on org.asteriskjava.manager.event.QueueStatusCompleteEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
May 05, 2016 7:49:40 PM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'listitems' to '1' on org.asteriskjava.manager.event.QueueStatusCompleteEvent: no setter. Please report at http://jira.reucon.org/browse/AJ

**Comment by seanbright** [comment]
Now tracked by #234
