### ISSUE TITLE
 WARNING: Unable to set property '' to 'AgentConnectEvent'

### ISSUE THREAD

**Issue by aahtesham** [asterisk-java/asterisk-java#137]
- Unable to set property 'destexten' to '600' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'destaccountcode' to '441142993721' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'destchannelstatedesc' to 'Up' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'channelstate' to '4' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'destuniqueid' to '' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'calleridname' to '' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'destconnectedlinename' to '' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'destcalleridname' to '202' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'priority' to '4' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'destcalleridnum' to '202' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'exten' to '600' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'accountcode' to '' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'connectedlinenum' to '202' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'calleridnum' to '07800656909' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'destpriority' to '1' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'destcontext' to '' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'channelstatedesc' to 'Ring' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'destchannel' to '' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'connectedlinename' to '202' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'destchannelstate' to '6' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'destconnectedlinenum' to '' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'interface' to '' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.
- Unable to set property 'context' to '' on org.asteriskjava.manager.event.AgentConnectEvent: no setter.

**Comment by Akshath0392** [comment]
Even I am getting these warning messages. Did any one find solution?

**Comment by bsutton** [comment]
they are not actually a problem unless you need to access that specific property on that specific event.
Essentially the event class is missing a setter for that property.

If you submit a patch we would be happy to accept it.

**Comment by scgm11** [comment]
the setters are there but seems the case of the property is wrong... should I lower the case of the properties?
