### ISSUE TITLE
No event class registered for event type 'contactstatus'

### ISSUE THREAD

**Issue by dafik** [asterisk-java/asterisk-java#141]
No event class registered for event type 'contactstatus', attributes: {roundtripusec=0, aor=151, privilege=system,all, uri=sip:151@10.0.11.142:5060, contactstatus=Unknown, endpointname=151, event=ContactStatus}.

https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerEvent_ContactStatus

**Comment by seanbright** [comment]
Now tracked in #235
