### ISSUE TITLE
Bad inplementation  handleOriginateEvent in org.asteriskjava.live.internal.AsteriskServerImpl

### ISSUE THREAD

**Issue by dafik** [asterisk-java/asterisk-java#145]
often event OriginateResponseEvent comes before NewStateEvent with chanelStatat = UP
current channel state is RINGING and callback is resolved with cb.onNoAnswer

**Comment by rlsutton1** [comment]
Yes with asterisk 13 the events sometimes arrive out of order. I think i have seen extension events arrive before newchannel events too.

I wonder if it might be useful to implement an event resequencer?  This would be useful for asterisk java internals and also help with users external legacy code

**Comment by bsutton** [comment]
I must say that resequencing scares me.

It implies delaying events until some other event arrives.
If that other event never arrives what happens then.

The approach I've taken previously is to write code that doesn't make 
unnecessary assumptions about the order of events.

e.g. as long as the both turn up then we can move forward.

The pairing of events may also not be consistent which would also be a 
problem for re sequencing.

We need to push our activity code out to the world as it deals with 
these problems be abstracting interaction to a higher level.

**Comment by dafik** [comment]
I'm not java programmer and code is not elegant but maybe it help someone:

there are two main changes:
- if response is failure callback resolves with cb.onFailure always.
- if channel state is ringing i add callback "ChannelStateChange"  
- ChannelCallback is extracted for not duplicate next logic

if you want to handle that state is not changed (event not come) you can add some kind of timeout



Code:

private void handleOriginateEvent(OriginateResponseEvent originateEvent) {
        final String traceId;
        final OriginateCallbackData callbackData;
        final OriginateCallback cb;
        final AsteriskChannelImpl channel;
        final AsteriskChannelImpl otherChannel; // the other side if local
        // channel

        class ChannelCallback {
            private boolean myResult;
            private OriginateCallback cb;
            private AsteriskChannelImpl channel;

            public ChannelCallback(OriginateCallback cb, AsteriskChannelImpl channel) {
                this.cb = cb;
                this.channel = channel;
            }

            boolean is() {
                return myResult;
            }

            public boolean invoke() {
                AsteriskChannelImpl otherChannel;
                if (channel.wasInState(ChannelState.UP)) {
                    cb.onSuccess(channel);
                    return true;
                }

                if (channel.wasBusy()) {
                    cb.onBusy(channel);
                    return true;
                }


                otherChannel = channelManager.getOtherSideOfLocalChannel(channel);
                // special treatment of local channels:
                // the interesting things happen to the other side so we have a look
                // at that
                if (otherChannel != null) {
                    final AsteriskChannel dialedChannel;

                    dialedChannel = otherChannel.getDialedChannel();

                    // on busy the other channel is in state busy when we receive
                    // the originate event
                    if (otherChannel.wasBusy()) {
                        cb.onBusy(channel);
                        return true;
                    }

                    // alternative:
                    // on busy the dialed channel is hung up when we receive the
                    // originate event having a look at the hangup cause reveals the
                    // information we are interested in
                    // this alternative has the drawback that there might by
                    // multiple channels that have been dialed by the local channel
                    // but we only look at the last one.
                    if (dialedChannel != null && dialedChannel.wasBusy()) {
                        cb.onBusy(channel);
                        return true;
                    }
                }

                // if nothing else matched we asume no answer
                cb.onNoAnswer(channel);
                return false;
            }
        }

        traceId = originateEvent.getActionId();
        if (traceId == null) {
            return;
        }

        synchronized (originateCallbacks) {
            callbackData = originateCallbacks.get(traceId);
            if (callbackData == null) {
                return;
            }
            originateCallbacks.remove(traceId);
        }

        cb = callbackData.getCallback();
        if (!AstUtil.isNull(originateEvent.getUniqueId())) {
            channel = channelManager.getChannelImplById(originateEvent.getUniqueId());
        } else {
            channel = callbackData.getChannel();
        }

        try {
            if (originateEvent.getResponse().equals("Failure")) {
                cb.onFailure(new NoSuchChannelException("reason" + originateEvent.getReason()));
                return;
            }

            if (channel == null) {
                final LiveException cause;

                cause = new NoSuchChannelException(
                        "Channel '" + callbackData.getOriginateAction().getChannel() + "' is not available");
                cb.onFailure(cause);
                return;
            }
            if (channel.getState().equals(ChannelState.RINGING)) {

                class ChannelStateChange implements PropertyChangeListener {

                    @Override
                    public void propertyChange(PropertyChangeEvent evt) {
                        if (evt.getPropertyName().equals(AsteriskChannel.PROPERTY_STATE)) {
                            channel.removePropertyChangeListener(this);
                            if (new ChannelCallback(cb, channel).invoke()) return;
                        }
                    }
                }

                channel.addPropertyChangeListener(new ChannelStateChange());
                return;
            }


            if (new ChannelCallback(cb, channel).invoke()) return;
        } catch (Throwable t) {
            logger.warn("Exception dispatching originate progress", t);
        }
    }

**Comment by bsutton** [comment]
I'm going to close this as I believe its an application level issue not an asterisk-java issue.

My recommendation to developers is to use the 'dial' activity as its designed to handled out of order events.
