### ISSUE TITLE
Unable to set property 'linkedid'

### ISSUE THREAD

**Issue by APKO** [asterisk-java/asterisk-java#158]
Unable to set property 'linkedid' to '1468925750.0' on org.asteriskjava.manager.event.HangupEvent: no setter.

**Comment by scgm11** [comment]
this is solved on commit 

https://github.com/asterisk-java/asterisk-java/commit/c460cee831bad1910ba399be5d51398f010da4b8#diff-b0b432dfb236b55925aec0419b290f3e
