### ISSUE TITLE
Missing response to QueuePause event

### ISSUE THREAD

**Issue by drencrom** [asterisk-java/asterisk-java#161]
I'm using asterisk java 1.1.0 with asterisk 11.13
Sometimes when I send a QueuePauseAction I receive a TimeoutException from the sendAction method of ManagerConnection.
Looking at the network traffic between asterisk and my server I see that the response arrives almost immediatly, well before the defined timeout period.
As it does not happen all the time I'm suspecting it could be a race condition in AsteriskJava.
I assume the ManagerConnection object is thread safe as I use it as a singleton injected by spring. I create it using the constructor of DefaultManagerConnection.

**Comment by drencrom** [comment]
Closing my own issue. The problem was that the AJ reader thread was blocking in a long event handler.

**Comment by bsutton** [comment]
Yes thats a common problem. We actually make the handlers async so as to never block the main thread.
Asterisk - Socket - Read - Enqueue - Dequeue - handler

The enqueue and dequeue happen on different threads.
This methods guarentees that you handle events in order whilst ensuring that the aj socket is never blocked.
You may also need one aj connection for writing (actions etc) and another for reading the responses.
