### ISSUE TITLE
 Unable to set property 'XYZ' on org.asteriskjava.manager.event.RtcpSentEvent 

### ISSUE THREAD

**Issue by vadermemo** [asterisk-java/asterisk-java#173]
Hi friends:

My application gets out the next log:

14:23:15,261 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'calleridname' to 'COARE.LUMA' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:15,261 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'channel' to 'SIP/1004-0000002c' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:15,261 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'language' to 'en' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:15,261 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'report0sourcessrc' to '0x10dcd417' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:15,261 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'exten' to '1000' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:15,261 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'report0dlsr' to '3.5621' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:15,261 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'calleridnum' to '<unknown>' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:15,261 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'context' to 'from-application' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:15,261 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'sentntp' to '1476904995.17576094117888' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:15,261 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'sentpackets' to '10429' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:15,262 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'sentrtp' to '2199873751' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:15,262 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'connectedlinenum' to '<unknown>' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:15,262 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'uniqueid' to '1476889673.78' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:15,262 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'channelstatedesc' to 'Up' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:15,262 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'reportcount' to '1' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,704 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'calleridname' to 'COARE.LUMA' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,704 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'channel' to 'SIP/1002-00000027' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,704 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'language' to 'en' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,704 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'report0sourcessrc' to '0x4806eeb2' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,704 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'exten' to '1000' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,704 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'report0dlsr' to '2.9410' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,704 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'calleridnum' to '<unknown>' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,704 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'context' to 'from-application' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,704 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'sentntp' to '1476905016.17574033350656' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,704 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'sentpackets' to '75183' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,704 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'sentrtp' to '2200042735' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,704 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'connectedlinenum' to '<unknown>' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,704 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'uniqueid' to '1476888397.64' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,705 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'channelstatedesc' to 'Up' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,705 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'reportcount' to '1' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,705 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'report0cumulativelost' to '2224' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,705 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'report0sequencenumbercycles' to '1' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,705 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'ssrc' to '0x0b911ebf' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,705 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'connectedlinename' to 'COARE.LUMA' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,705 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'priority' to '4' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,705 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'report0highestsequence' to '39370' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,705 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'channelstate' to '6' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,705 WARN  [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'report0fractionlost' to '0' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
14:23:38,706 ERROR [org.asteriskjava.manager.internal.EventBuilderImpl](Asterisk-Java ManagerConnection-0-Reader-0) Unable to set property 'rtt' to '0.2210' on org.asteriskjava.manager.event.RtcpReceivedEvent: java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.asteriskjava.manager.internal.AbstractBuilder.setAttributes(AbstractBuilder.java:132)
    at org.asteriskjava.manager.internal.EventBuilderImpl.buildEvent(EventBuilderImpl.java:321)
    at org.asteriskjava.manager.internal.ManagerReaderImpl.buildEvent(ManagerReaderImpl.java:348)
    at org.asteriskjava.manager.internal.ManagerReaderImpl.run(ManagerReaderImpl.java:224)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "0.2210"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Long.parseLong(Long.java:589)
    at java.lang.Long.parseLong(Long.java:631)
    at org.asteriskjava.manager.event.AbstractRtcpEvent.secStringToLong(AbstractRtcpEvent.java:101)
    at org.asteriskjava.manager.event.RtcpReceivedEvent.setRtt(RtcpReceivedEvent.java:202)
    ... 8 more

thanks a lot for your help.

Best regards.

**Comment by towe75** [comment]
Hi,

i run into the same issue with 1.1.0 Beta and started to look at the code.

1.1.0 Beta tries to parse RTT into a integer but in Master it is already double. So it looks like this bug was already resolved in commit https://github.com/asterisk-java/asterisk-java/commit/d734ea6 

Regards

**Comment by vadermemo** [comment]
Hi again,
  I am using this maven

<dependency>

    <groupId>org.asteriskjava</groupId>

    <artifactId>asterisk-java</artifactId>

    <version>1.0.0-final</version>

</dependency>


  This version have the problem.


Best regards.



2016-10-28 1:28 GMT-05:00 Thomas Weber <notifications@github.com>:

**Comment by towe75** [comment]
A quick check in 1.0.0-final Tag tells me that it had the same bug. 
As stated: it was fixed in master, see d734ea6 (May 2015)

Currently there seems to be no binary available. Also in branch 1.1 it is not fixed.
Only workaround so far is to build your own Jar from master.

**Comment by seanbright** [comment]
This is resolved as of Asterisk-Java 2.0.2 which is available from Maven Central.
