### ISSUE TITLE
asterisk version detection for agi

### ISSUE THREAD

**Issue by rlsutton1** [asterisk-java/asterisk-java#174]
create a static concurrentHashMap to hold ip -> AsteriskVersion

extend AsteriskVersion to store the delimiter.

when an agi arrives, lookup the ip in the map, if not existent then determine the asterisk version

create a thread local for the agi to get the current AsteriskVersion

modify existing AGI commands to use the correct delimiter

also modify ConnectionImpl to use the map for getting the asterisk version, this will mask the issue where after an asterisk restart AJ fails to detect the asterisk version

**Comment by seanbright** [comment]
Since Asterisk 1.6.0, the Asterisk version is sent as one of headers (`agi_version`) after Asterisk connects to the FastAGI server.

**Comment by bsutton** [comment]
We could use this fact and assume if there is no agi_version header then the version is 1.4.
