### ISSUE TITLE
 No event class registered for event type 'fullybooted'

### ISSUE THREAD

**Issue by bamirsbajraktari** [asterisk-java/asterisk-java#176]
Hi , i ma trying to make calls from vtiger 6.5.0 with Asterisk Connector 1.4 , when i use context vtiger as from vtiger PBXManager page , when i click dhe number on vtiger ,call comes on  3cx phone, when i click answer call hangs up immediately ,i have attached the log .
 Thanks !

[asterisk connector webapp log.txt](https://github.com/asterisk-java/asterisk-java/files/548141/asterisk.connector.webapp.log.txt)

**Comment by seanbright** [comment]
Now tracked in #235
