### ISSUE TITLE
Question regarding StatusEvent attributes

### ISSUE THREAD

**Issue by vmatic** [asterisk-java/asterisk-java#180]
Hi,

this question should be probably addressed to asterisk.org but since there I can only find confusing  and incomplete documentation regarding of semantics of attributes I decided to ask here. Also I'm aware this isn't an issue with asterisk-java. 

I can't fully comprehend semantics of the following attributes within `StatusEvent` `linkedId` and `uniqueId`. I think these attributes could also be found in some other events generated by AMI. My understanding is that attribute `channel` uniquely identifies a channel so I don't see why `uniqueId` is introduced? Similar thing with `linkedId`, does it have same semantics as `bridgeId`? I'm using latest version of asterisk-java from master and Asterisk 13.

Thanks in advance.

Best regards,

Viktor

**Comment by bsutton** [comment]
I'm closing as this isn't an asterisk-java issue.
