### ISSUE TITLE
Unable to set property 'connectedlinename' and Unable to set property 'connectedlinenum'

### ISSUE THREAD

**Issue by danielgarciapro** [asterisk-java/asterisk-java#184]
WARN 22572 --- [tion-0-Reader-0] o.a.manager.internal.EventBuilderImpl    : Unable to set property 'connectedlinename' to 'XXXXXXXX' on org.asteriskjava.manager.event.StatusEvent: no setter.

WARN 22572 --- [tion-0-Reader-0] o.a.manager.internal.EventBuilderImpl    : Unable to set property 'connectedlinenum' to 'XXXXXXXX' on org.asteriskjava.manager.event.StatusEvent: no setter.

**Comment by scgm11** [comment]
fixed in https://github.com/asterisk-java/asterisk-java/pull/188/commits/ea8fa4cd4a862fa0b0d26f21ce4d47e968c451c7
