### ISSUE TITLE
Command Response format for Asterisk 14+

### ISSUE THREAD

**Issue by bodunov** [asterisk-java/asterisk-java#185]
23:32:31.568 [Asterisk-Java ManagerConnection-0-Reader-0] WARN org.asteriskjava.manager.internal.ResponseBuilderImpl - Unable to set property 'output' to '[key  : /family1/key1, , key  : /family2/key2, ]' on org.asteriskjava.manager.response.CommandResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues

**Comment by bodunov** [comment]
Latest versions of Asterisk have a different result for "Command" action, which breaks the existing response building functionality.
This is what you get when you execute "Command" action:
 
Response: Success
ActionID: 1
Message: Command output follows
Output: key  : /family1/key1
Output:
Output: key  : /family2/key2
Output:

So, there is no anymore "Follows" response, there is no "--END COMMAND--" line, as expected by current implementation and tests. The response now has to be handled differently and CommandResponse should contain "output" field.

Any comments to that?

**Comment by bodunov** [comment]
From: https://wiki.asterisk.org/wiki/display/AST/Upgrading+to+Asterisk+14 :

- The Command action now sends the output from the CLI command as a series of Output headers for each line instead of as a block of text with the --END COMMAND-- delimiter to match the output from other actions.

- Commands that fail to execute (no such command, invalid syntax etc.) now return an Error response instead of Success.

It explains why current implementation fails. It is not ready yet for the above changes.

**Comment by seanbright** [comment]
Fixed by e88d7eb72ae669893275220b311a33cb56739675
