### ISSUE TITLE
 Unable to set property 'lastreload' / Unable to set property 'uptime' 

### ISSUE THREAD

**Issue by bodunov** [asterisk-java/asterisk-java#186]
23:32:30.353 [Asterisk-Java ManagerConnection-0-Reader-0] WARN org.asteriskjava.manager.internal.EventBuilderImpl - Unable to set property 'lastreload' to '39441' on org.asteriskjava.manager.event.FullyBootedEvent: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
23:32:30.353 [Asterisk-Java ManagerConnection-0-Reader-0] WARN org.asteriskjava.manager.internal.EventBuilderImpl - Unable to set property 'uptime' to '42059' on org.asteriskjava.manager.event.FullyBootedEvent: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues

**Comment by scgm11** [comment]
fixed in https://github.com/asterisk-java/asterisk-java/pull/188/commits/060979e63e518319994a66160350bc68cb91914a
