### ISSUE TITLE
Unable to set property 'output' to 'No such command 'show version files pbx.c'

### ISSUE THREAD

**Issue by bodunov** [asterisk-java/asterisk-java#187]
23:32:30.459 [Asterisk-Java ManagerConnection-0-Reader-0] WARN org.asteriskjava.manager.internal.ResponseBuilderImpl - Unable to set property 'output' to 'No such command 'show version files pbx.c' (type 'core show help show version' for other possible commands)' on org.asteriskjava.manager.response.ManagerError: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues

**Comment by scgm11** [comment]
fixed in https://github.com/asterisk-java/asterisk-java/pull/188/commits/c17a8cc90cb876e9530ecc1fc9ac0c5d03acc7a4

**Comment by seanbright** [comment]
So then this should be closed?
