### ISSUE TITLE
Unable to set property 'accountcode' to 'False'

### ISSUE THREAD

**Issue by danielgarciapro** [asterisk-java/asterisk-java#191]
WARN 10189 --- [tion-0-Reader-0] o.a.manager.internal.EventBuilderImpl    : Unable to set property 'accountcode' to 'False' on org.asteriskjava.manager.event.HangupEvent: no setter. Please report at http://jira.reucon.org/browse/AJ

**Comment by seanbright** [comment]
Now tracked in #234
