### ISSUE TITLE
Asterisk-Java ManagerConnection-0-Reader-0

### ISSUE THREAD

**Issue by feroom** [asterisk-java/asterisk-java#201]
2017.06.16 06:34:04 WARN  [Asterisk-Java ManagerConnection-0-Reader-0]: org.asteriskjava.manager.internal.EventBuilderImpl - Unable to set property 'statustext' to 'Idle' on org.asteriskjava.manager.event.ExtensionStatusEvent: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
2017.06.16 06:36:00 WARN  [socket_c2s-thread-3]: class org.jivesoftware.openfire.streammanagement.StreamManager[192.168.1.1] - Client acknowledges stanzas that we didn't send! Client Ack h: 65, our last stanza: 58

**Comment by bsutton** [comment]
Can you submit a patch with the necessary setter?

**Comment by bsutton** [comment]
closed as no further response.
