### ISSUE TITLE
NewConnectedLineEvent missing from the jar release

### ISSUE THREAD

**Issue by MINDoSOFT** [asterisk-java/asterisk-java#203]
Hello everyone,

I am wondering why the class NewConnectedLineEvent appears in the source code but is not included in the jar release of asterisk-java.

At least not in versions Asterisk-java-1.0.0.final and Asterisk-Java 1.1.0 Beta.

Thanks in advance,

Sergios.

**Comment by bsutton** [comment]
We simply haven't had time to build and push a new release.
You will need to build your own version from source.
Sorry.
