### ISSUE TITLE
ManagerResponse getAttribute(keyname) got null

### ISSUE THREAD

**Issue by YangChihLin** [asterisk-java/asterisk-java#208]
I was trying to get the channel variable via ```GetVarAction```
when I invoked ```getAttribute("variableName")```  but I got a null.
After dump all the attributes by ``` getAttributes() ```
I found that I should invoke ```getAttribute("value")``` so that I can get the real value corresponding to the key "variableName".

for instance:

I have a channel variable "MyVar" with value "MyValue"

```java
value =  res.getAttribute("variable"); // got "MyVar"
value =  res.getAttribute("value");    // got "MyValue"
value =  res.getAttribute("MyVar");    // null
```

Is that a bug?

**Comment by molekyla** [comment]
No it is not. You should get value by invoking GetVarResponse.getValue() method

**Comment by YangChihLin** [comment]
Oh, I see, thanks a lot!
