### ISSUE TITLE
Version clarification

### ISSUE THREAD

**Issue by drenda** [asterisk-java/asterisk-java#209]
I'm using from a while the beta 1 version of Asterisk Java. I took a look at commits made and I saw there are a lot of changes.

I saw there isn't any recent snapshot on sonatype. I know I can clone the project and build on my machine, but my question is: is the code stable right now?

When do you think will be realeased another official release of Asterisk Java?

Thanks

**Comment by bsutton** [comment]
We are using the code in production.
The main area of new code is with the activities, which aren't documented as yet, so I would guess that no one is using them except for noojee.

**Comment by bsutton** [comment]
closed as v2 has now been released.
