### ISSUE TITLE
compiling 

### ISSUE THREAD

**Issue by mahan77** [asterisk-java/asterisk-java#211]
Trying to compile asterisk-java in NetBeans 8.2 mac OS X 10.12.5.
Getting this error, any help please?

------------------------------------------------------------------------
Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:3.2.0:bnd-process (default) on project asterisk-java: Execution default of goal biz.aQute.bnd:bnd-maven-plugin:3.2.0:bnd-process failed: A required class was missing while executing biz.aQute.bnd:bnd-maven-plugin:3.2.0:bnd-process: org/slf4j/LoggerFactory
-----------------------------------------------------
realm =    plugin>biz.aQute.bnd:bnd-maven-plugin:3.2.0
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/Users/Sathees/.m2/repository/biz/aQute/bnd/bnd-maven-plugin/3.2.0/bnd-maven-plugin-3.2.0.jar
urls[1] = file:/Users/Sathees/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
urls[2] = file:/Users/Sathees/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
urls[3] = file:/Users/Sathees/.m2/repository/biz/aQute/bnd/biz.aQute.bndlib/3.2.0/biz.aQute.bndlib-3.2.0.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------: org.slf4j.LoggerFactory
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

**Comment by bsutton** [comment]
can you try doing a build using the maven cli and report the results.

**Comment by bsutton** [comment]
closed a no followup.
