### ISSUE TITLE
The connection indicates that Socket closed can login normally with telnet. The address, username and password are all correct

### ISSUE THREAD

**Issue by sunlad1** [asterisk-java/asterisk-java#220]
The connection indicates that Socket closed can login normally with telnet. The address, username and password are all correct
This is my code
![image](https://user-images.githubusercontent.com/27797771/33112730-a5cf36d4-cf8f-11e7-884a-0bf0494ecd5d.png)
This is wrong information 
![image](https://user-images.githubusercontent.com/27797771/33112739-b3c62220-cf8f-11e7-8ce6-762fe22fc242.png)
Log in through telnet 
![image](https://user-images.githubusercontent.com/27797771/33112766-d4ca1a76-cf8f-11e7-8820-568df496490f.png)
Ask God for help

**Comment by bsutton** [comment]
You might want to change your password now :)

What are the asterisk logs saying?

**Comment by sunlad1** [comment]
There is no hint

**Comment by sunlad1** [comment]
![image](https://user-images.githubusercontent.com/27797771/33114530-32f5b134-cf98-11e7-9f85-2d0336221d01.png)
I've changed the password and restarted the asterisk, but not yet

**Comment by sunlad1** [comment]
I've found the reason, but I don't know how to solve it 
![image](https://user-images.githubusercontent.com/27797771/33165827-2e74c812-d073-11e7-8c80-58b28d0f9f8b.png)
Here, determine the information returned by asterisk ,What the program wants to return is "Asterisk Call Manager/1.1" but actually what's returned is "asterisk Call Manager/1.1".
![image](https://user-images.githubusercontent.com/27797771/33165975-9829693e-d073-11e7-9f63-766e95448df6.png)
I've changed the jar version, but not yet

**Comment by bsutton** [comment]
Can you send a pull request.

Perhaps the correct solution is to do a case insensitive match.
I must say it does surprise me that its coming back with lower case 'asterisk'.
