### ISSUE TITLE
I can't find org.asteriskjava.pbx package

### ISSUE THREAD

**Issue by caligula95** [asterisk-java/asterisk-java#221]
Can you help me? I try to write java-asterisk app and started to do tutorials from this repo. But I can't find anything that connected with pbx. 
I tried to download the latest library Asterisk Java » 1.1.0-beta and anothers but it didn't work.
Any suggestions?

**Comment by bsutton** [comment]
We have just pushed V2 to the maven repository.

You will need that version.

Search maven Central to find it.

**Comment by bsutton** [comment]
I believe this is dealt with so closing out.
