### ISSUE TITLE
EAgi Script to stream audio and capture dtmf events

### ISSUE THREAD

**Issue by narrow89** [asterisk-java/asterisk-java#222]
Hi. Im having trouble to make work this case. I've a eagi script workin that stream the audio written on a filedescriptor and send it to other platform. But now i need to capture if user send a dtmf.
I've tried with mannanger api, but didn't work.
Can Someone Helpme with that?

Thanks.

**Comment by bsutton** [comment]
The manager API should work for getting DTMF events, can you provide more
details on what you are doing?

**Comment by narrow89** [comment]
I have a script that extends from BaseAgiScript. In the service method i have a loop that send frame buffers of the audio stream to another platform. Now, i tried to create an object like the example of Hello Events from http://asterisk-java.org/tutorial/
When event ocur i can print that event (like VarSetEvent)...but when i press a digit on my phone, expectin a dtmf event...that not ocur and the script die.
I have the HelloEvents runing in a Thread.

Thanks

**Comment by bsutton** [comment]
What do you mean the script dies?

Remove the eagi code for the moment whilst you sort out the DTMF issue.

Post the event loop code

**Comment by bsutton** [comment]
Just a bit of feed back.

When asking questions on these type of forums you need to be far more 
explicit about what you are doing and in particular what went wrong as 
apposed to what you expected to occur.

Terms like 'and the script die' indicates that this is a key area of 
concern but you provide no useful information that would allow anyone to 
help you.

You should be looking to see if an exception has been thrown and report 
the associated stack trace in full.
You should have a try/catch Throwable at the top of each thread which 
dumps any exception.

If the application appeared to 'lockup' then you need to provide a 
thread dump of the application.
If you are running linux you can generate a thread dump by running:
sudo kill -QUIT <pid no. of your appliciation>

Always be explict and provide as much information as you can.

Brett

**Comment by narrow89** [comment]
Hi Brett. Thanks for the reply. I was able to solve the problem.

**Comment by bsutton** [comment]
So what was the issue?

**Comment by narrow89** [comment]
I made a separate jar for dtmf event listener and notice that the events was ocurring as espected. The problem was in my script, that have a control for the status of the channel. When someone send dtmf tome, my script had beign interrupted.
