### ISSUE TITLE
AsteriskPBX.checkDialplanExists uses wrong command for Asterisk 13

### ISSUE THREAD

**Issue by think01** [asterisk-java/asterisk-java#224]
I'm using asterisk-java 2.0.2 with Asterisk 13.
It correctly recognizes Asterisk version on startup.
AsteriskPBX.checkDialplanExists() uses the command "show dialplan PROFILE" but it gets this error:

```
No such command 'show dialplan asteriskjava' (type 'core show help show dialplan' for other possible commands)
```

The right command for this version of Asterisk is: "dialplan show". Is this a bug or there's something I'm missing?

Thanks in advance for any hint.

**Comment by bsutton** [comment]
I would guess that this is a backwards comparability issue.  Looks like we need some conditional code to handle older versions of asterisk. The existing command should be executed for versions prior to 13 and the new command for 13+.
If you would like to push a code change that would be great.

**Comment by seanbright** [comment]
@think01 a workaround would be to install `res_clialiases.so`, and create a file at `/etc/asterisk/cli_aliases.conf` with the following contents:

```
[general]
template = backwards_compat

[backwards_compat]
show dialplan=dialplan show
```

**Comment by seanbright** [comment]
FYI - The CLI command was changed from `show dialplan` to `dialplan show` between Asterisk 1.4 and Asterisk 1.6.0.

**Comment by bsutton** [comment]
My preference has always to not force users to have to customize their asterisk config any more than necessary so I'm not keen on the backwards compatibility issue.

I'm going to ask rsutton to review with respect to getVersion working when running inside fast agi.
