### ISSUE TITLE
Missing setters for manager responses

### ISSUE THREAD

**Issue by pikzen** [asterisk-java/asterisk-java#240]
Upon startup, it looks like the library is trying to register setters for all the commands available as a logged in user.
Now, I am aware that the protocol used in our Asterisk 15.1 is not supported (`Asterisk Call Manager/4.0.1`), and that the issues might stem from that, but I might as well let you know about the issues that pop up. Tell me if you'd like the list of modules enabled if that can make your life easier, or anything else. I am currently using the latest Maven version of the library, with parts being overridden manually (such as support for Asterisk 15, which is not in Maven yet)

> WARN  [2018-02-15 13:34:51,303] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'agi' to 'Add an AGI command to execute by Async AGI.  (Priv: agi,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,304] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'dahdidialoffhook' to 'Dial over DAHDI channel while offhook.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,304] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'getconfigjson' to 'Retrieve configuration (JSON format).  (Priv: system,config,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,304] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'bridgetechnologysuspend' to 'Suspend a bridging technology.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,304] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'dialplanextensionremove' to 'Remove an extension from the dialplan  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,305] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'messagesend' to 'Send an out of call message to an endpoint.  (Priv: message,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,305] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'aocmessage' to 'Generate an Advice of Charge message on a channel.  (Priv: aoc,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,305] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'meetmelist' to 'List participants in a conference.  (Priv: reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,305] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'waitevent' to 'Wait for an event to occur.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,305] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'controlplayback' to 'Control the playback of a file being played to a channel.  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,305] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'extensionstatelist' to 'List the current known extension states.  (Priv: call,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,306] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'muteaudio' to 'Mute an audio stream.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,306] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'presencestate' to 'Check Presence State  (Priv: call,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,306] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'bridgekick' to 'Kick a channel from a bridge.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,306] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'coreshowchannels' to 'List currently active channels.  (Priv: system,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,306] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'sorcerymemorycacheexpire' to 'Expire (remove) ALL objects from a sorcery memory cache.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,306] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'bridgetechnologyunsuspend' to 'Unsuspend a bridging technology.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,306] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'logoff' to 'Logoff Manager.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,308] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'mixmonitormute' to 'Mute / unMute a Mixmonitor recording.  (Priv: system,call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,308] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'bridge' to 'Bridge two channels already in the PBX.  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,308] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'userevent' to 'Send an arbitrary event.  (Priv: user,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,308] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'listcategories' to 'List categories in configuration file.  (Priv: config,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'pjsipshowregistrationsoutbound' to 'Lists PJSIP outbound registrations.  (Priv: system,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'status' to 'List channel status.  (Priv: system,call,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'sorcerymemorycachestaleobject' to 'Mark an object in a sorcery memory cache as stale.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'ping' to 'Keepalive command.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'login' to 'Login Manager.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'meetmelistrooms' to 'List active conferences.  (Priv: reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'pjsipshowsubscriptionsinbound' to 'Lists subscriptions.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'dahdidndoff' to 'Toggle DAHDI channel Do Not Disturb status OFF.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'unpausemonitor' to 'Unpause monitoring of a channel.  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'redirect' to 'Redirect (transfer) a call.  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'dbdel' to 'Delete DB entry.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'pjsipqualify' to 'Qualify a chan_pjsip endpoint.  (Priv: system,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'mailboxcount' to 'Check Mailbox Message Count.  (Priv: call,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'meetmeunmute' to 'Unmute a Meetme user.  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,309] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'pjsipshowsubscriptionsoutbound' to 'Lists subscriptions.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'filter' to 'Dynamically add filters for the current manager session.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'dbput' to 'Put DB entry.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'moduleload' to 'Module management.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'dahdihangup' to 'Hangup DAHDI Channel.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'devicestatelist' to 'List the current known device states.  (Priv: call,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'loggerrotate' to 'Reload and rotate the Asterisk logger.  (Priv: system,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'pjsipshowendpoint' to 'Detail listing of an endpoint and its objects.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'setvar' to 'Sets a channel variable or function value.  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'meetmemute' to 'Mute a Meetme user.  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'absolutetimeout' to 'Set absolute timeout.  (Priv: system,call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'localoptimizeaway' to 'Optimize away a local channel when possible.  (Priv: system,call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'sorcerymemorycachepopulate' to 'Expire all objects from a memory cache and populate it with all objects from the backend.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'hangup' to 'Hangup channel.  (Priv: system,call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'pausemonitor' to 'Pause monitoring of a channel.  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'voicemailuserslist' to 'List All Voicemail User Information.  (Priv: call,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'getvar' to 'Gets a channel variable or function value.  (Priv: call,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'bridgedestroy' to 'Destroy a bridge.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'pjsipshowendpoints' to 'Lists PJSIP endpoints.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'stopmixmonitor' to 'Stop recording a call through MixMonitor, and free the recording's file handle.  (Priv: system,call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'corestatus' to 'Show PBX core status variables.  (Priv: system,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'cancelatxfer' to 'Cancel an attended transfer.  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'createconfig' to 'Creates an empty file in the configuration directory.  (Priv: config,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'updateconfig' to 'Update basic configuration.  (Priv: config,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'originate' to 'Originate a call.  (Priv: originate,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'pjsipunregister' to 'Unregister an outbound registration.  (Priv: system,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,310] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'sorcerymemorycachestale' to 'Marks ALL objects in a sorcery memory cache as stale.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'dbdeltree' to 'Delete DB Tree.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'presencestatelist' to 'List the current known presence states.  (Priv: call,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'changemonitor' to 'Change monitoring filename of a channel.  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'dbget' to 'Get DB Entry.  (Priv: system,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'dahditransfer' to 'Transfer DAHDI Channel.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'dahdidndon' to 'Toggle DAHDI channel Do Not Disturb status ON.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'bridgelist' to 'Get a list of bridges in the system.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'blindtransfer' to 'Blind transfer channel(s) to the given destination  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'pjsipregister' to 'Register an outbound registration.  (Priv: system,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'bridgetechnologylist' to 'List available bridging technologies and their statuses.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'coresettings' to 'Show PBX core settings (version etc).  (Priv: system,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'bridgeinfo' to 'Get information about a bridge.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'extensionstate' to 'Check Extension Status.  (Priv: call,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'reload' to 'Send a reload event.  (Priv: system,config,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'pjsipshowregistrationinboundcontactstatuses' to 'Lists ContactStatuses for PJSIP inbound registrations.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'mailboxstatus' to 'Check mailbox.  (Priv: call,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'dahdirestart' to 'Fully Restart DAHDI channels (terminates calls).  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,311] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'sendtext' to 'Send text message to channel.  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'voicemailrefresh' to 'Tell Asterisk to poll mailboxes for a change  (Priv: user,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'dialplanextensionadd' to 'Add an extension to the dialplan  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'modulecheck' to 'Check if module is loaded.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'pjsipshowresourcelists' to 'Displays settings for configured resource lists.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'getconfig' to 'Retrieve configuration.  (Priv: system,config,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'mixmonitor' to 'Record a call and mix the audio during the recording.  Use of StopMixMonitor is required to guarantee the audio file is available for processing during dialplan execution.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'monitor' to 'Monitor a channel.  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'atxfer' to 'Attended transfer.  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'command' to 'Execute Asterisk CLI Command.  (Priv: command,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'pjsipshowregistrationsinbound' to 'Lists PJSIP inbound registrations.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'listcommands' to 'List available manager commands.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'sorcerymemorycacheexpireobject' to 'Expire (remove) an object from a sorcery memory cache.  (Priv: system,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'dahdishowchannels' to 'Show status of DAHDI channels.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'challenge' to 'Generate Challenge for MD5 Auth.  (Priv: <none>)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,312] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'showdialplan' to 'Show dialplan contexts and extensions  (Priv: config,reporting,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
WARN  [2018-02-15 13:34:51,313] org.asteriskjava.manager.internal.ResponseBuilderImpl: Unable to set property 'stopmonitor' to 'Stop monitoring a channel.  (Priv: call,all)' on org.asteriskjava.manager.response.ManagerResponse: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues

**Comment by bsutton** [comment]
Thanks for the post but the reality is that the only way this will move forward is if someone pushes code to support the event/attributes.
I'm closing this for now. Re-open if you think it needs further discussion.

**Comment by pikzen** [comment]
I'm absolutely willing to implement quite a few of those, can you just check and tell me if what it does is intended behavior?

It seems to me like it is trying to parse the response sent from the server (Listing its commands in the form `<command>          <description>`) and trying to fill out a ManagerResponse from it. Should the ManagerResponse have an attribute for each of those commands? It seems weird to me. Let me know if you'd like a dump of what the server answers when connecting to it.
