### ISSUE TITLE
Missing ChannelId (Channel UniqueID) as an attribute of OriginateAction class

### ISSUE THREAD

**Issue by tcervi** [asterisk-java/asterisk-java#241]
I'm current playing around with this great project and I know that the [FAQs Section](http://asterisk-java.org/faq/) is already guiding us about how to handle the ChannelIDs from OriginateActions sent via ManagerConnection: 

>"(...) track the events the Manager API emits, if you encounter a NewChannelEvent get the variable from that channel and match it to a call. From there on you can use the channel name to track events."

But I was just wondering why don't give the user access to the ChannelId when creating the OriginateAction? On [asterisk wiki](https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerAction_Originate) it's possible to verify that  the "**ChannelId: value**" is an available Argument to be used on the Originate Action Syntax.

> "ChannelId - Channel UniqueId to be set on the channel."

The advantage of this is that you previously know the uniqueId associated with your Originated call, so you just need to ensure that the Response was successful and avoid the "overhead" of handling the Asterisk events.

I know that it's not a big overhead, but if can be avoided, why not?

If you find this a good idea, I can try to code it and make a PR with this insertion.

**Comment by tcervi** [comment]
@bsutton it's on asterisk wiki (AMI Actions) since version 12

**Comment by bsutton** [comment]
So we are looking at creating version 3.x of asterisk java.
The idea is that 3.x will abandon support for older version of asterisk.
The question that I will be proposing is which versions do we abandon.
So I'm thinking that this type of change should go in the new 3.x branch.

**Comment by tcervi** [comment]
@bsutton fair enough. I agree with you, so this can be implemented on 3.x version once it is started.

**Comment by tcervi** [comment]
So @bsutton, the idea would be to overload: originateToExtension, originateToApplication, originateToExtensionAsync and originateToApplicationAsync on AsteriskServer interface and AsteriskServerImpl.
Are you ok with it? I'm proceeding with the implementation and after some tests will submit the PR.

**Comment by rlsutton1** [comment]
added channelId and otherChannelId to OriginateAction
commit 594782f0371f2d3af201c826b1aa30742e848923 #

**Comment by tcervi** [comment]
Hi @rlsutton1 sorry for my late answer here. I've moved from that project for a while and just now played with it again. 

Tested your code and it works fine when creating the OriginateAction object and setting it's properties. Should we stick to those setters or also overload AsteriskServer/AsteriskServerImpl methods that originate calls (including 'channelId' as a parameter)?

**Comment by piotrooo** [comment]
Fixed since 3.0.10.
