### ISSUE TITLE
Should not force log4j as a dependency

### ISSUE THREAD

**Issue by michaelkrog** [asterisk-java/asterisk-java#243]
asterisk-java is using slf4j(https://github.com/asterisk-java/asterisk-java/blob/master/pom.xml#L190) which makes it easy to user the logging framework by choice, but at the same time it forces the use of log4j(https://github.com/asterisk-java/asterisk-java/blob/master/pom.xml#L184).

This may cause issues in the application using the lib. For example a vanilla spring boot application will immediately complain during startup and logging will be broken. Fix is to exclude the log4j dependency, when depending on asterisk-java.

**Comment by bsutton** [comment]
closing as I'm expecting the push to be accepted shortly.
