### ISSUE TITLE
missing properties and type error

### ISSUE THREAD

**Issue by scgm11** [asterisk-java/asterisk-java#245]
Unable to convert value: Called the constructor of class java.lang.Integer with value '18778032399' for the attribute 'parkeeconnectedlinenum'

a

**Comment by scgm11** [comment]
@bsutton can you give me access so I can push branches and create pull request?

**Comment by scgm11** [comment]
I know about that but we talked with bsutton to give me access some time ago, I have made some pull request that way

**Comment by bsutton** [comment]
you should have received an invite.
