### ISSUE TITLE
WARNING: Unable to create AgiScript instance of type org.asteriskjava.pbx.agi.ActivityAgi

### ISSUE THREAD

**Issue by boopac** [asterisk-java/asterisk-java#250]
Hi,
I am using  asterisk-java-2.0.2.jar and Asterisk 14.7.5.
I am running asterisk on one server and asterisk-java for FastAGI-Support on another server.

I am doing
`java -jar asterisk-java-2.0.2.jar`
and it start correctly.
`
Mai 16, 2018 6:29:39 PM org.asteriskjava.fastagi.DefaultAgiServer startup
INFO: Listening on *:4573.
`

If I check the dial example i am getting the following error:
```
WARNING: Unable to create AgiScript instance of type org.asteriskjava.pbx.agi.ActivityAgi
java.lang.InstantiationException
        at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.asteriskjava.fastagi.AbstractMappingStrategy.createAgiScriptInstance(AbstractMappingStrategy.java:145)
        at org.asteriskjava.fastagi.ResourceBundleMappingStrategy.loadResourceBundle(ResourceBundleMappingStrategy.java:175)
        at org.asteriskjava.fastagi.ResourceBundleMappingStrategy.determineScript(ResourceBundleMappingStrategy.java:191)
        at org.asteriskjava.fastagi.AbstractMappingStrategy.determineScript(AbstractMappingStrategy.java:51)
        at org.asteriskjava.fastagi.CompositeMappingStrategy.determineScript(CompositeMappingStrategy.java:115)
        at org.asteriskjava.fastagi.internal.AgiConnectionHandler.run(AgiConnectionHandler.java:132)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Mai 16, 2018 6:35:37 PM org.asteriskjava.fastagi.internal.AgiConnectionHandler run
SEVERE: No script configured for URL 'agi://192.168.120.53/activityAgi.agi' (script 'activityAgi.agi')
```
This is the standard agi-script with `createAgiEntryPoint()` is putting in the extensions of asterisk.

What's wrong?
Maybe someone can help.

Regards,
Boris

**Comment by boopac** [comment]
I am doing a async dial

First initialize the asterisk connection:
`
private void initAsterisk() {
	/*
    	 * Initialise the PBX Factory. You need to implement your own AsteriskSettings class.
    	 */
        MyAsteriskSettings settings = new MyAsteriskSettings(); 
        PBXFactory.init(settings);
        this.trunk = settings.getTrunk();

        /*
         * Activities utilise an agi entry point in your dial plan.
         * You can create your own entry point in dialplan or have
         * asterisk-java add it automatically as we do here.
         */
        try {
            this.asteriskPbx = (AsteriskPBX) PBXFactory.getActivePBX();
	    boolean entryPoint = myCreateAgiEntryPoint();
            // using of my own createAgiEntryPoint, because of the known problem of
            // show dialplan ... (old asterisk version)
            // now it's dialplan show ...
            //			boolean entryPoint = this.asteriskPbx.createAgiEntryPoint();

		AlertDialog.showInfoDialog("Asterisk-Anmeldung", String.format("Asterisk-Initialisierung erfolgreich: %s"	, this.asteriskPbx.getVersion().toString()));
			
        } catch (IOException e) {
		e.printStackTrace();
	} catch (AuthenticationFailedException e) {
		e.printStackTrace();
	} catch (TimeoutException e) {
		e.printStackTrace();
	} catch (Exception e) {
		e.printStackTrace();
	}		
}
`

The connection is successful!

Now i am doing the async dial:
`      
       public void dial(String hauptleitung, String nebenstelle, String nummer) {
		
        try {
            PBX pbx = PBXFactory.getActivePBX();

            // We are going to dial from extension 100 to 5551234
            
            // The trunk MUST match the section header (e.g. [default]) that appears
            // in your /etc/asterisk/sip.d file (assuming you are using a SIP trunk).
            // The trunk is used to select which SIP trunk to dial through.
            Trunk trunk = pbx.buildTrunk(hauptleitung);

            // We are going to dial from extension 100
            EndPoint from = pbx.buildEndPoint(TechType.SIP, nebenstelle);
            // Provide confirmation to the agent which no. we are dialing by
            // showing it on their handset.
            CallerID fromCallerID = pbx.buildCallerID(nummer, "Wählt...");

            // The caller ID to display on the called parties phone.
            // On most systems the caller id name part won't display
            CallerID toCallerID = pbx.buildCallerID(nummer, "POS wählt Rufnummer");
            // The party we are going to call.
            EndPoint to = pbx.buildEndPoint(TechType.SIP, trunk, nummer);

            // Start the dial and return immediately.
            // progress is provided via the ActivityCallback.
            pbx.dial(from, fromCallerID, to, toCallerID, new ActivityCallback<DialActivity>() {

                @Override
                public void progress(DialActivity activity, ActivityStatusEnum status, String message) {
                    if (status == ActivityStatusEnum.SUCCESS) {
                        System.out.println("Dial all good");
                        try {
                            // Call is up
                            Call call = activity.getNewCall();
                            // So lets just hangup the call
                            // logger.warn("Hanging up");
                            PBXFactory.getActivePBX().hangup(call.getOriginatingParty());

                        } catch (PBXException e) {
                            System.out.println(e);
                        }
                    }
                    if (status == ActivityStatusEnum.FAILURE)
                        System.out.println("Oops something bad happened when we dialed.");
                }
            });

        } catch (Exception e) {
            System.out.println(e);
        }
 }
`

If i am dialing, the agi-host throws the InstantiationException and the dial is interrupted.

I have create a file fastagi-mapping.properties
`activityAgi.agi=org.asteriskjava.pbx.agi.ActivityAgi`
`hello.agi = HelloAgiScript`

and put it in the asterisk-java-2.0.2.jar file.

**Comment by seanbright** [comment]
`org.asteriskjava.pbx.agi.ActivityAgi` is an abstract class, and therefore cannot be instantiated.
