### ISSUE TITLE
Create version 3.x of asterisk-java and abandon support for older versions.

### ISSUE THREAD

**Issue by bsutton** [asterisk-java/asterisk-java#251]
We are now seeing some breaking changes coming from new versions of asterisk and community demand for those new changes.
We can either continue to try and support both the newer version and the older ones or create a new branch and leave the older version to be supported by the 2.x branch.

I'm inclined to abandon the old versions in 3.x

If we do this what is the earliest version that 3.x should support?

Add comments to give you opinion!

**Comment by bsutton** [comment]
Yes I would agree on the java 8 idea.

**Comment by bsutton** [comment]
what about java 9 so we get modules?
A like the idea of not contaminating some else project with all our dependencies.
I'm not certain if you can use a java 9 lib from a java 8 app?

**Comment by scgm11** [comment]
yes actually I said java 8 but I was thinking at least java 8

**Comment by seanbright** [comment]
Java 9 is not an LTS. My vote would be either Java 8 or Java 11 once it is released. You can build JARs that work with both Java 8 & 9 but I have not done it personally.

**Comment by bsutton** [comment]
I don't think LTS is actually an issue from the a library perspective, its more of a runtime issue ( you want an runtime that has security patches).

Having said that I think the reality is that most of the world is still on Java 8 and as a library we probably need to stay behind the curve.

Internally we are thinking Java 8, asterisk 13 is probably a reasonable combo.
We can do minor maintenance fixed on asterisk-java 2.x to support pre 13  if required but I think the library is pretty stable so would expect many changes (baring some missing events).

So any strong objections to  java 8/asterisk 13?

**Comment by cincarnato** [comment]
I agree Java 8 / Asterisk 13

**Comment by Erbos** [comment]
I think that java 8 and asterisk 13 is an excellent choice.

**Comment by bsutton** [comment]
So java 8 and asterisk 13 it is :)

**Comment by tcervi** [comment]
Java 8 and Asterisk 13 sounds good! 
Any planned date to start the new branch? :)

**Comment by Polve** [comment]
Is there any progress of that?

I think Java 11 as a baseline now makes sense for v3.

**Comment by nbruning** [comment]
I'm seeing published 3.x versions, I guess this issue can be closed.

**Comment by piotrooo** [comment]
Closed in favour of #405
