### ISSUE TITLE
Is it possible to package AgiScripts and asterisk-java into an uber/fat jar for deployment?

### ISSUE THREAD

**Issue by brandon-haugen** [asterisk-java/asterisk-java#256]
I am just starting a project that is using asterisk-java and to make the deployment of and running of the application a bit easier I would like to package up the asterisk-java jar as well as the classes that extend BaseAgiScript into one uber/fat jar.

I have tried to do this already, however, Asterisk does not seem to be able to find my custom BaseAgiScript class when it is packaged in a jar. Asterisk prints out

> agi://192.168.1.91/hello.agi: No script configured for URL 'agi://192.168.1.91/hello.agi' (script 'hello.agi')

If I run asterisk-java without packaging everything into a jar, then it finds my custom BaseAgiScript with no problem so that makes me think that the mapping strategy is where I would need to customize asterisk-java so that it can find classes in the jar instead.

Or I am missing something and am completely wrong. Any help would be greatly appreciated!

**Edit:** It could also be that the fastagi-mapping.properties file is not being found either, I need to check that as well.

**Comment by bsutton** [comment]
The uber jat is certainly not the problem

**Comment by bsutton** [comment]
Have you checked that you app is listening on the AGI the port

**Comment by brandon-haugen** [comment]
@bsutton, if I run asterisk-java with my classes when they are not packaged as a Jar everything works fine. It is just when I package them into a Jar that it stops working.

I don't know of any reason why packaging the classes into a Jar would change the port so I would assume that even when running from the Jar the port did not change. Maybe there is something I am missing though about running asterisk-java from my uber Jar though.

When running from the uber Jar, it looks like I don't have logging setup correctly because the port info that the DefaultAgiServer class logs is not being printed to the console so I might have other configuration issues to work through.

Knowing that you believe the uber Jar though is not the problem is good though and I will keep working on getting this to work in my project.

Are there any recommendations on how applications built with asterisk-java should be packaged/deployed? I didn't see anything in the documentation or examples that show it and I would assume that that is just because all of the normal Java packaging methods are okay to use.

Thanks!

**Comment by seanbright** [comment]
@brandon-haugen can you provide a repository that replicates your problem? If so I can take a look.

**Comment by bsutton** [comment]
Given that you logging is also not working the problem is definitely going
to be your class path.

Asterisk Java has no special requirements.

**Comment by bsutton** [comment]
Also look at
StaticMappingStrategy

This will allow you to put the mapping in your code.

Personally I don't like the properties file as it's a passion you to use.

**Comment by brandon-haugen** [comment]
Thanks again @bsutton and @seanbright, I finally got back to this and got it functional. I think what I missed the first time around was making sure the mapping file made it into the result JAR. I ended up switching the mapping strategy anyways though so all of the above tips were really helpful!
