### ISSUE TITLE
Migration Guide (No script configured for URL 'AGI://localhost/xxx.agi' (script 'xxx.agi').)

### ISSUE THREAD

**Issue by NoMaillard** [asterisk-java/asterisk-java#261]
Hii all,

I'm currently working on moving a project from asterisk-java 1.0 to 2.0. And as you can expect i'm having a little trouble. I always end up having the same error `No script configured for URL 'AGI://localhost/xxx.agi' (script 'xxx.agi')`.
I'm following tutorials on different websites and most refer to the 1.0 version. and i was wondering if there was a migration guide, or at least a list of the main breaking changes.

Thanks in advance

**Comment by lbotton** [comment]
Same problem here.

**Comment by seanbright** [comment]
[The tutorial on asterisk-java.org](https://asterisk-java.org/tutorial/) seems correct to me. If you follow that and still have problems please let us know.
