### ISSUE TITLE
help to use dial

### ISSUE THREAD

**Issue by gabrielmatau79** [asterisk-java/asterisk-java#267]
Hi! i build new proyect witch asterisk-java library, i need help to use de example class Dial , to compile send error for reference asterisk setting, (you must call setAsteriskSettings() before getActiveProfile() is called the first time) this error comes from not having the sip sever configured in the library i need to know how to do it please..!
regards!!

**Comment by oNuoyi** [comment]
may i ask how this problem was solved，i also reproduced it
