### ISSUE TITLE
Get member in call for each queue

### ISSUE THREAD

**Issue by danillocesar** [asterisk-java/asterisk-java#271]
I have a list of queues from the server and inside that i have a list of members of that queue. I need to know if the member is in call on that specific queue. Can somebody give me a hint?

Inside AsteriskQueueMember i have only if the device is in use, but for all queues that he is on.

I have this snippet:

```
for (AsteriskQueue queue : queues) {
        	//members of the queue
        	for(AsteriskQueueMember member : queue.getMembers()) {
        		//need to know if the member is in call on THIS specific list
        		//member.getState() returns DEVICE_IN_USE for all queues, not the one that he is indeed in a call
        		
        	}
        }
```

**Comment by biguitarman** [comment]
From 2.0.2 Asterisk java version, you can get status by queue.

Saludos!
