### ISSUE TITLE
Unable to set property 'privilege' to 'SMSCommand'

### ISSUE THREAD

**Issue by Niemi** [asterisk-java/asterisk-java#272]
Hi to all.
in release 2.0.2 we have waring:

Unable to set property 'privilege' to 'SMSCommand' on org.asteriskjava.manager.response.ManagerResponse: no setter.

Brgs,
Niemi

**Comment by seanbright** [comment]
I can't find `SMSCommand` in any version of Asterisk going back to 1.4 - what kind of Asterisk server is this coming from?

**Comment by seanbright** [comment]
I'm going to close this for now because I don't feel this is an asterisk-java issue, but feel free to comment if you disagree and I will re-open it.
