### ISSUE TITLE
SO_TIMEOUT for *AgiServer

### ISSUE THREAD

**Issue by adrien-martin** [asterisk-java/asterisk-java#274]
Hello,

The commit cf4605756b06cb9c8b1f1b6a62c9b7a1d98d618f (*agi tcp connection hang-up protection) set SO_TIMEOUT to 4200s on sockets.
The commit c70aeea75dca2998959f9095bb37beba084b5b16 ([AJ-49] Added setReadTimeout(int) to DefaultManagerConnection) allow modifying this timer on ManagerConnection with setSocketReadTimeout(int).

Is there any way to set this timer on *AgiServer ?
Alternate question, the second commit add a PingThread class for keepalives, does AGI have a similar keepalive feature ?

Context :
AGI calls longer than 4200s trigger "org.asteriskjava.fastagi.AgiHangupException: Channel was hung up" in exec("Dial").
4200s is not that long for a phone call.

**Comment by rlsutton1** [comment]
Hi @adrien-martin,

You are correct that 4200s for a call is not long. 

I expect that the channel will remain bridged despite the AGI connection collapsing, do you know if this is correct?

Currently there is no way to configure the read timeout.

I'll suggest that it should be a configuration option when creating the AGI server, do you have any thoughts on a sensible default value - presumably longer than 4200s.

AGI does not have a "keep alive" function, I'm not sure if that would even be possible as I assume (may be wrong) that the AGI call is blocking during actions like dial.

**Comment by adrien-martin** [comment]
Hi @rlsutton1,

> I expect that the channel will remain bridged despite the AGI connection collapsing, do you know if this is correct?

This is correct, Asterisk channels are not hung up, and still bridged, caller and callee do not notice.
Only further AGI operations are affected.

> [...] do you have any thoughts on a sensible default value - presumably longer than 4200s.

In our use case we need a timer longer than 4 hours (would probably set something like 4h15), but as long as it is configurable 4200s is ok too.
I don't know what is an acceptable timeout for other users.
Infinite/0 should probably accepted as a configuration value.

I'm currently working on a patch.
