### ISSUE TITLE
Unable to determine protocol version Asterisk Call Manager/4.0.3

### ISSUE THREAD

**Issue by devabdicant** [asterisk-java/asterisk-java#276]
Hi,
I get a nice log:
[ERROR] - Unable to determine asterisk version, assuming 1.6... you should expect problems to follow.
  and previously I get 
[INFO ] - Connected via Asterisk Call Manager/4.0.3
[WARN ] - Unsupported protocol version 'Asterisk Call Manager/4.0.3'. Use at your own risk.

In ManagerConnectionImpl.java line 1333 says to show that log if no IF condition is found, but I see that condition on line 1328. I don't really understand why it keeps showing me the warning. Is it causing the first ERROR?

All data I get from logger is this, from the moment it logs in, line 596
11:54:37.910 [INFO ] - Successfully logged in
11:54:37.910 [DEBUG] - Dispatching event:
org.asteriskjava.manager.event.FullyBootedEvent[dateReceived='Tue Oct 23 11:54:37 CEST 2018',privilege='system,all',lastreload='2419949',server=null,calleridname=null,systemname=null,connectedlinename=null,sequencenumber=null,priority=null,exten=null,channelstate=null,uptime='2419949',calleridnum=null,context=null,connectedlinenum=null,status='Fully Booted',channelstatedesc=null,timestamp=null,systemHashcode=620108350]
11:54:37.911 [DEBUG] - Dispatching response with internalActionId '2097823593_2':
org.asteriskjava.manager.response.ManagerError: actionId='null'; message='Command output follows'; response='Error'; uniqueId='null'; systemHashcode=2128548617
11:54:37.912 [DEBUG] - Dispatching response with internalActionId '2097823593_3':
org.asteriskjava.manager.response.CommandResponse: actionId='null'; message='Command output follows'; response='Success'; uniqueId='null'; systemHashcode=506780912
11:54:38.414 [DEBUG] - Dispatching response with internalActionId '2097823593_4':
org.asteriskjava.manager.response.ManagerError: actionId='null'; message='Command output follows'; response='Error'; uniqueId='null'; systemHashcode=1321287480
11:54:38.416 [DEBUG] - Dispatching response with internalActionId '2097823593_5':
org.asteriskjava.manager.response.CommandResponse: actionId='null'; message='Command output follows'; response='Success'; uniqueId='null'; systemHashcode=1216359090
11:54:38.918 [DEBUG] - Dispatching response with internalActionId '2097823593_6':
org.asteriskjava.manager.response.ManagerError: actionId='null'; message='Command output follows'; response='Error'; uniqueId='null'; systemHashcode=2058786662
11:54:38.920 [DEBUG] - Dispatching response with internalActionId '2097823593_7':
org.asteriskjava.manager.response.CommandResponse: actionId='null'; message='Command output follows'; response='Success'; uniqueId='null'; systemHashcode=1113397148
11:54:39.430 [DEBUG] - Dispatching response with internalActionId '2097823593_8':
org.asteriskjava.manager.response.ManagerError: actionId='null'; message='Command output follows'; response='Error'; uniqueId='null'; systemHashcode=86169616
11:54:39.440 [DEBUG] - Dispatching response with internalActionId '2097823593_9':
org.asteriskjava.manager.response.CommandResponse: actionId='null'; message='Command output follows'; response='Success'; uniqueId='null'; systemHashcode=1287567292
11:54:39.941 [ERROR] - Unable to determine asterisk version, assuming 1.6... you should expect problems to follow.

When I enter 'core show version' then my asterisk says 'Asterisk 15.3.0-rc2 built by root @ localhost.localdomain on a x86_64 running Linux ' in case this helps you.

Thanks for the help!!!

**Comment by YangChihLin** [comment]
I faced this issue, too.
I am trying Asterisk16 and asterisk-java:2.0.3, seems asterisk-java hasn't support newer version yet

**Comment by rlsutton1** [comment]
master - 3.0.0 is intended to support asterisk 16.
this fix is now merged to master
