### ISSUE TITLE
FastAGI, AgiChannel.dial() bug.

### ISSUE THREAD

**Issue by realpg** [asterisk-java/asterisk-java#286]
I use asterisk-java as a fastagi server.
The script doesn't work as expert when use channel.dial() method.

Turn on asterisk debug mode, I found that the channel.dial("PJSIP/8888",45,"a") method sent a message to asterisk as this format:

Dial("PJSIP/8888|45|a")

My asterisk 13 needs to receive like this:

Dial("PJSIP/8888",45,a)

I must use 

channel.exec("Dial", "PJSIP/8888,45,a") instead to let it work as expected.

The dial method is totally broken.

**Comment by bsutton** [comment]
Which version of asterisk-java are you using?

You need to use the v2 for asterisk 13 support.
