### ISSUE TITLE
Unable to set property 'trunkname' to 

### ISSUE THREAD

**Issue by KostasC22** [asterisk-java/asterisk-java#287]
Hello, I am getting this warning in my asterisk java app, I am using 2.0.2 version.

2019-02-04 10:24:01 WARN  EventBuilderImpl:83 - Unable to set property 'trunkname' to 'trunkregisteration' on org.asteriskjava.manager.event.RegistryEvent: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues

**Comment by bsutton** [comment]
Its just a warning you can safely ignore it unless you need access to 
that property.

**Comment by KostasC22** [comment]
It is ok, if I create the missing setters and then commit it back to the this repository?

**Comment by quaerosys** [comment]
I get the same warning for 12 properties a few times per call which is pretty annoying. I'm using version 3.2.0 with Asterisk 16.2.1 and I didn't have this issue with older Asterisk versions. How can this be solved?

**Comment by bsutton** [comment]
You would need to push a patch that contained the new properties for the
affected events.
