### ISSUE TITLE
org.asteriskjava.manager.event.BridgeLeaveEvent: no setter

### ISSUE THREAD

**Issue by allanj53** [asterisk-java/asterisk-java#290]
06-Mar-2019 22:51:47.098 WARNING [Asterisk-Java ManagerConnection-0-
Reader-0]
org.asteriskjava.manager.internal.AbstractBuilder.setAttributes Unable
to set property 'bridgevideosourcemode' to 'none' on
org.asteriskjava.manager.event.BridgeLeaveEvent: no setter. Please
report at https://github.com/asterisk-java/asterisk-java/issues

Added getters and setters to BridgeLeaveEvent are attached:
--------------------------------------------------------------------------------------------------------------

package org.asteriskjava.manager.event;

/**
 * Created by Alexander Polakov <apolyakov@beget.ru> on 1/26/15.
 */
public class BridgeLeaveEvent extends AbstractBridgeEvent
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String uniqueId;
	private String channel;
	private String language;
	private String linkedId;
        private String bridgevideosourcemode;
	
	public BridgeLeaveEvent(Object source)
	{
		super(source);
	}

	public String getLanguage()
	{
		return language;
	}

	public void setLanguage(String language)
	{
		this.language = language;
	}

	public String getUniqueId()
	{
		return uniqueId;
	}

	public void setUniqueId(String uniqueId)
	{
		this.uniqueId = uniqueId;
	}

	public String getChannel()
	{
		return channel;
	}

	public void setChannel(String channel)
	{
		this.channel = channel;
	}

        public String getLinkedId()
        {
            return linkedId;
        }

        public void setLinkedId(String linkedId)
        {
            this.linkedId = linkedId;
        }
        
        public String getBridgevideosourcemode ()
        {
            return this.bridgevideosourcemode;
        }

        public void setBridgevideosourcemode (String bridgevideosourcemode) {
            this.bridgevideosourcemode = bridgevideosourcemode;
        }
  
}

**Comment by PatrykGalwa** [comment]
Added. To close
