### ISSUE TITLE
Asterisk version 16 and this version of library

### ISSUE THREAD

**Issue by ramin-git** [asterisk-java/asterisk-java#293]
Hi.
Is this version of library compatible with Asterisk 16?

**Comment by rlsutton1** [comment]
I'm currently using master in development with asterisk 16

**Comment by ramin-git** [comment]
> I'm currently using master in development with asterisk 16
Thanks the answer. What do you think how long can it will made?
We work with new version of Asterisk. And we want to use java lib which compatible with this version.

**Comment by yong-jae-kim** [comment]
i'm sorry my english is bad

i am using asterisk-java .2.0.2

i feel 
when i log in to asterisk 16 ami
very slower than asterisk 13 ami

**Comment by nbruning** [comment]
We have successfully run AsteriskJava 3.x with Asterisk 16 in production.
