### ISSUE TITLE
ConfBridgeListAction problem

### ISSUE THREAD

**Issue by Daveron1981** [asterisk-java/asterisk-java#304]
Hi,

Is there any way to get data about all active conferences?

    		ConfbridgeListAction confListAction = new ConfbridgeListAction( );
                managerConnection.sendAction(confListAction);

Is not working. This request can be used to get data only about specific conference (so you must set conference attribute)

    		confListAction.setConference("12345");

Without this attribute there is no response,

Is there any way to get send ConfBridgeListAction to get data from all active conferences?

Something similar to: "confbridge list" from console?

Thanks and best regards!

**Comment by bsutton** [comment]
What do you mean when you say that its not working?
I haven't checked this method but generally the result is returned
asynchronously.

**Comment by Daveron1981** [comment]
Hi,
Thanks for answer, 

If you will execute:

ConfbridgeListAction confListAction = new ConfbridgeListAction( );
confListAction.setConference("12345");
managerConnection.sendAction(confListAction);

Data with participants of conference 12345 are returned in ConfbridgeListEvents, and this is working

I you will execute this request without conferenceId system will not return even a single ConfbridgeListEvent. Without conferenceId this request is ignored. 

How to ask about all participants in all conferences? 

Im working on asterisk 16.

Best regards!

**Comment by Daveron1981** [comment]
My mistake. I didnt noticed ConfBridgeListRoomsAction,

Thanks very much!

PS: ConfbridgeListEvent does not have "talking" and "muted" attributes. But those attributes are present in AMI response. If someone will mute participant, using this method you cannot obtain info if user is muted, 

I added them myself in compiled code. But someone else can have this problem. Just FYI, 

Thanks!
