### ISSUE TITLE
java.net.SocketException: Broken pipe (Write failed) 

### ISSUE THREAD

**Issue by ardiqwerty** [asterisk-java/asterisk-java#313]
Hi, I got many errors after sendAction (call) more than 100 calls.

java.net.SocketException: Broken pipe (Write failed) 
Timeout waiting for response to Originate

Everything was good if the calls less than 50.

Could you help me?

**Comment by scgm11** [comment]
are you originating async? are you going to fast on generating? if you are generation to a provider does your provider support the cps that you are doing?

**Comment by seanbright** [comment]
It sounds like you are overloading Asterisk. There is nothing we can do on the asterisk-java side to help with that. You should decrease the number of originates you are doing or decrease the rate that you are performing originates.
