### ISSUE TITLE
Unsupported protocol version 'Asterisk Call Manager/5.0.1'. Use at your own risk.

### ISSUE THREAD

**Issue by gmilit** [asterisk-java/asterisk-java#314]
When hooking up asterisk-java to my freePBX server running freePBX 14 I get the following errors. 

Unsupported protocol version 'Asterisk Call Manager/5.0.1'. Use at your own risk.
`o.a.manager.internal.ManagerConnectionImpl - Unsupported protocol version 'Asterisk Call Manager/5.0.1'. Use at your own risk.
o.a.manager.internal.ManagerConnectionImpl - Unable to determine asterisk version, assuming 1.6... you should expect problems to follow.`

Is there something I have to do to get this running?

**Comment by bsutton** [comment]
It will more than likely run.
You could add the version to .a.manager.internal.ManagerConnectionImpl and
map it to the appropriate asterisk version.

**Comment by nbruning** [comment]
This should be fixed by #294, so try to update to 3.0.10 or higher.

**Comment by timo-klarshift** [comment]
This issue can be closed
