### ISSUE TITLE
There's no action/events - PJSIPShowContacts, ContactList, ContactListComplete, ContactStatusDetail at Asterisk 16

### ISSUE THREAD

**Issue by hsunryou** [asterisk-java/asterisk-java#315]
I'm using Asterisk 16.5.1
There's no Action/Events in Asterisk 16 

action - PJSIPShowContacts
Events - ContactList, ContactListComplete, ContactStatusDetail

**Comment by piotrooo** [comment]
`PJSIPShowContacts` and `ContactStatusDetail` available since 3.9.0.
`ContactList` and `ContactListComplete` available since 3.2.0.
