### ISSUE TITLE
org.asteriskjava.util.ReflectionUtil fails load event classes when bundled inside another jar

### ISSUE THREAD

**Issue by tareqmy** [asterisk-java/asterisk-java#318]
I was using asterisk-java 3.0.2 by building jar. i used it in a spring boot application. it worked fine when ran directly from the Intellij Idea. Recently i was moving from development to production. so i build the spring boot application into a jar. when i run the jar using java -jar myapp.jar... reflectionUtil says Loaded 0. and all kinds of manager events fail.

14:17:17.346  INFO [       Thread-3] org.asteriskjava.util.ReflectionUtil     : >/development/projects/myapp/build/libs/myapp-web-1.0.0-SNAPSHOT.jar
14:17:17.350  INFO [       Thread-3] org.asteriskjava.util.ReflectionUtil     : Loaded 0

**Comment by santino83** [comment]
I had the same problem: in a more complex scenario, the classloader used by reflectionutil is not able to detect the event classes from org.asteriskjava.manager.event. I ended up manually loading those classes into the EventBuilder when creating the connection to the manager. Here my solution:

pom:
```
<!-- reflection -->
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.9.12</version>
        </dependency>
```

java:

```

import org.reflections.Reflections;
import java.lang.reflect.Modifier;
import org.asteriskjava.manager.ManagerConnection;
import org.asteriskjava.manager.event.ManagerEvent;
import java.util.Set;

...

protected void registerCustomEvents(ManagerConnection managerConnection)
    {
        // register all native asteriskjava events.
        // it overrides the way used by natve library to find and load event classes
        Reflections reflections = new Reflections("org.asteriskjava.manager.event");
        Set<Class<? extends ManagerEvent>> events = reflections.getSubTypesOf(ManagerEvent.class);
        events.stream()
                .filter(clazz -> !Modifier.isAbstract(clazz.getModifiers()) && !clazz.isInterface())
                .forEach(eventClass -> managerConnection.registerUserEventClass(eventClass));
        
        // register custom events
        managerConnection.registerUserEventClass(MyCustomEventClass.class);
    }

```

It needs an external dependency (reflections) but this library handle better the way to discover classes in classpath

**Comment by rlsutton1** [comment]
I've done a build with EventBuilderImpl using org.reflections.
It's 3.0.23-SNAPSHOT, it should be available in maven central later today.
#a2e6e13791e4999f1e4b7a1c1615ab7aba039952
