### ISSUE TITLE
Erroneous BridgeEvent events created by backwards compatibility layer.

### ISSUE THREAD

**Issue by discardedwutu** [asterisk-java/asterisk-java#330]
asterisk-java cleverly creates BridgeEvent events out of BridgeEnterEvent events when the count of channels in a bridge reaches two. The only trouble with this is that not all channels that enter a bridge are actually being bridged together. Example:

1.SIP/a calls SIP/b
2.SIP/b parks call
    SIP/a enters parking bridge
3.SIP/c calls SIP/b
4.SIP/b parks call
    SIP/c enters parking bridge
    asterisk-java recognizes that a bridge has two channels now
    asterisk-java generates a BridgeEvent indicating that SIP/a and SIP/c are connected to one another

Parking uses what is known as a holding bridge -- a system for keeping channels in the bridging architecture, but while they are in these bridges they don't really communicate with each other in any way and it's not accurate to connect them.

Trivial fix is to add a conditional check on the bridge technology to make sure the bridge isn't a holding bridge before doing doing the whole backwards compatibility thing.

**Comment by discardedwutu** [comment]
relevant block of code starts at

main/java/org/asteriskjava/manager/internal/backwardsCompatibility/bridge/BridgeState.java:47

**Comment by bsutton** [comment]
Would you be able to push a patch?

**Comment by discardedwutu** [comment]
I will attempt to do so within the next few hours.

**Comment by discardedwutu** [comment]
Alright, I made a pull request. Let me know if you need anything else.

**Comment by rlsutton1** [comment]
thanks
