### ISSUE TITLE
Unable to determine asterisk version, assuming Asterisk 13... you should expect problems to follow.

### ISSUE THREAD

**Issue by AhmadHamdanMontyMobile** [asterisk-java/asterisk-java#334]
core show version:
    Asterisk certified/16.8-cert2 built by...

In your code:
    private static final String VERSION_PATTERN_16 = "^\\s*Asterisk (GIT-)?16[-. ].*";

Should be:
    private static final String VERSION_PATTERN_16 = "^\\s*Asterisk (GIT-)?(certified/)?16[-. ].*";

OR:
    private static final String VERSION_PATTERN_CERTIFIED_16 = "^\\s*Asterisk certified/(GIT-)?16[-. ].*";

**Comment by bsutton** [comment]
Could you push a pr with the change.
