### ISSUE TITLE
Memory leak in AsteriskQueueImpl

### ISSUE THREAD

**Issue by bbankowski** [asterisk-java/asterisk-java#336]
Scenario:
`QueueManager.handleJoinEvent` and `QueueManager.handleQueueEntryEvent` check for duplicates using `AsteriskQueueImpl.getEntry`. Then a new entry is created via `AsteriskQueueImpl.createNewEntry`.

Problem:
When `createNewEntry` is invoked more than once at the same time it may add duplicates. There is no synchronization in between of checking for duplicates and creating new entry. If duplicate is added it will never be removed.

In my case it happens when `AsteriskServerImpl.forceQueuesMonitor` is enabled and `createNewEntry` is invoked as a result of caller entering queue and Asterisk response to `QueueStatusAction`.

**Comment by bsutton** [comment]
Can you provide pr with a fix,?

**Comment by bbankowski** [comment]
It is here #337

**Comment by rlsutton1** [comment]
pr merged
