### ISSUE TITLE
channelshunguplistcomplete

### ISSUE THREAD

**Issue by juniorlatalisa** [asterisk-java/asterisk-java#340]
No event class registered for event type 'channelshunguplistcomplete', attributes: {eventlist=Complete, listitems=2, actionid=1240197940_14#, event=ChannelsHungupListComplete}. Please report at https://github.com/asterisk-java/asterisk-java/issues

**Comment by seanbright** [comment]
The ability to hangup multiple channels via regex was [added to Asterisk a long time ago](https://github.com/asterisk/asterisk/commit/e4252eac1010af969007afb525871242855d39e7), but we don't currently handle it.

I don't see a clean way to handle it, other than creating a new `HangupMultipleAction` that extends `EventGeneratingAction`, but I will think on it.
