### ISSUE TITLE
QueueListener onNewEntry onEntryLeave not fired on asterisk version >= 13

### ISSUE THREAD

**Issue by sioux1977** [asterisk-java/asterisk-java#342]
After asterisk 11 events JoinEvent and LeaveEvent (used by QueueManager to fire event listeners) are not used anymore. From Asterisk v13 and over, the new events QueueCallerJoinEvent and QueueCallerLeaveEvent are used.
Latest version of asterisk-java i have tried (3.6.1) still use older one. I wrote a little patch for asterisk-java 3.6.1 to handle both cases.
[AsteriskQueueImpl.diff.txt](https://github.com/asterisk-java/asterisk-java/files/5057400/AsteriskQueueImpl.txt)
[queuemanager.diff.txt](https://github.com/asterisk-java/asterisk-java/files/5057401/queuemanager.txt)

**Comment by piotrooo** [comment]
`QueueManager` uses both - `LeaveEvent` and `QueueCallerLeaveEvent`, this is done for backward compatibility.
