### ISSUE TITLE
INFO: Resource bundle 'fastagi-mapping' not found.

### ISSUE THREAD

**Issue by SiddharthChabukswar** [asterisk-java/asterisk-java#343]
Hi,

I'm new to asterisk and Java. I installed asterisk java from 'source'  following the steps mentioned in Readme. 

I tried running the example/fastagi/ExampleCallIn.java file. It compiled and ran successfully but when I make a call I get the following issue:

Aug 12, 2020 9:42:47 AM org.asteriskjava.fastagi.ResourceBundleMappingStrategy loadResourceBundle
INFO: Resource bundle 'fastagi-mapping' not found.

The script inside isn't getting  executed. 

I've followed the ReadME step by step without any alterations. And also added the jar in example/fastagi/ dir.

Please help
![Asterisk-JavaError](https://user-images.githubusercontent.com/42469248/90023755-b881a080-dcd1-11ea-952c-32e5631f03e2.PNG)

**Comment by bsutton** [comment]
It will be a problem with your class path.

The mapping file must be located in a directory on your class path.


Try putting it in classes.

**Comment by piotrooo** [comment]
If you have any other questions feel free to reopen this issue or create a new one.
