### ISSUE TITLE
org.asteriskjava.manager.event.ParkedCallGiveUpEvent: no setter.

### ISSUE THREAD

**Issue by sadzas** [asterisk-java/asterisk-java#355]
ParkedCallGiveUpEvent Event.

Very simple: On unparking I get this issue.

org.asteriskjava.manager.internal.EventBuilderImpl  | Unable to set property 'parkeelinkedid' to '1604327571.139' on org.asteriskjava.manager.event.ParkedCallGiveUpEvent: no setter.

Also ParkedCallGiveUpEvent Event is missing in AbstractManagerEventListener

**Comment by piotrooo** [comment]
Fixed in 3.35.0
