### ISSUE TITLE
Unsupported protocol version 'Asterisk Call Manager

### ISSUE THREAD

**Issue by jrcmoura** [asterisk-java/asterisk-java#357]
Good day everyone, Could you help me solve this error?

Got asterisk protocol identifier version Asterisk Call Manager/2.10.4
Determined Asterisk version: Asterisk 13
Closing socket

Apache NetBeans IDE 12.1
Java: 14.0.1; Java HotSpot(TM) 64-Bit Server VM 14.0.1+

all error message:
[main] INFO org.asteriskjava.manager.internal.ManagerConnectionImpl - Connecting to 192.168.15.15:5038
[main] INFO org.reflections.Reflections - Reflections took 288 ms to scan 1 urls, producing 31 keys and 209 values 
[Asterisk-Java ManagerConnection-0-Reader-0] INFO org.asteriskjava.manager.internal.ManagerConnectionImpl - Connected via Asterisk Call Manager/2.10.4
[Asterisk-Java ManagerConnection-0-Reader-0] WARN org.asteriskjava.manager.internal.ManagerConnectionImpl - Unsupported protocol version 'Asterisk Call Manager/2.10.4'. Use at your own risk.
[main] INFO org.asteriskjava.manager.internal.ManagerConnectionImpl - Successfully logged in
Error
[main] INFO org.asteriskjava.manager.internal.ManagerConnectionImpl - Got asterisk protocol identifier version Asterisk Call Manager/2.10.4
[main] INFO org.asteriskjava.manager.internal.ManagerConnectionImpl - Determined Asterisk version: Asterisk 13
[main] INFO org.asteriskjava.manager.internal.ManagerConnectionImpl - Closing socket.
BUILD SUCCESSFUL (total time: 0 seconds)

**Comment by bsutton** [comment]
Unsupported protocol version 'Asterisk Call Manager/2.10.4'. Use at your
own risk.

This is just a warning.

Do you have an actual problem?

When posting an issue you need to provide far more details on what the
issue is.  We simply can't help you with the information provided.

**Comment by timo-klarshift** [comment]
This issue likely is happening because AMI version 2.10 is not defined in the code base:

org.asteriskjava.manager.internal.ManagerConnectionImpl:

```
private static final String[] SUPPORTED_AMI_VERSIONS = {

            "2.6", // Asterisk 13
            "2.7", // Asterisk 13.2
            "2.8", // Asterisk >13.5
            "2.9", // Asterisk >13.3
            "3.1", // Asterisk =14.3
            "3.2", // Asterisk 14.4.0
            "4.0", // Asterisk 15
            "5.0", // Asterisk 16
            "6.0", // Asterisk 17
            "7.0", // Asterisk 18
    };
    
```
One could simply provide a PR with 2.10 there, but to fix this for other edge cases one solution would be to add some semver matching compared to some fixed mapping.

**Comment by brabo-hi** [comment]
Hi, any solution? i still have the same issue ` [WARN] [org.asteriskjava.manager.internal.ManagerConnectionImpl] Unsupported protocol version 'Asterisk Call Manager/9.0.0'. Use at your own risk` even though i am using version `3.36.0`

**Comment by piotrooo** [comment]
Asterisk 20 sets AMI version to 9.0.

**Comment by brabo-hi** [comment]
> Asterisk 20 sets AMI version to 9.0.

How can i solve this issue and have this warning turned off

**Comment by piotrooo** [comment]
Use version 3.36.1 with fix for this.

**Comment by brabo-hi** [comment]
> Use version 3.36.1 with fix for this.

Here is the error I am getting when using version `3.36.1`
` [ERROR] [org.asteriskjava.manager.internal.ManagerConnectionImpl] Unable to determine asterisk version, assuming Asterisk 16... you should expect problems to follow.`

**Comment by piotrooo** [comment]
@brabo-hi 3.37.0 should resolve this bug. Let me know it everything is ok.

**Comment by brabo-hi** [comment]
yes it is solved. Thanks
