### ISSUE TITLE
dongleportfail in vtiger

### ISSUE THREAD

**Issue by hithamadel2004** [asterisk-java/asterisk-java#358]
i install vitiger in issabel 4 with chan-dongle /asterisk 11.25
after add SPAsteriskConnector-1.4.2 give me this massage
[Asterisk-Java ManagerConnection-0-Reader-0] INFO org.asteriskjava.manager.internal.EventBuilderImpl - No event class registered for event type 'dongleportfail', attributes: {privilege=call,all, message=Response Failed, event=DonglePortFail, device=/dev/ttyUSB5}. Please report at https://github.com/asterisk-java/asterisk-java/issues

update java and apache-maven-3.6.0
and stay problem
please i need solve this problem
thanks

**Comment by bsutton** [comment]
It's just a warning. You can safely ignore it.

**Comment by hithamadel2004** [comment]
thanks alot
but now when click number of client apper massage (Pick up the extension receiver to dial the number) but nothing happend
i add number  admin in CRM Phone Extension

**Comment by bsutton** [comment]
That feels like a question for the vtiger Devs.
