### ISSUE TITLE
NumberFormatException: For input string: "true"

### ISSUE THREAD

**Issue by 1001v** [asterisk-java/asterisk-java#360]
Hello. I've successfully created my own [PJSIPShowRegistrationsOutbound](https://wiki.asterisk.org/wiki/display/AST/Configuring+Outbound+Registrations) action, as well as OutboundRegistrationDetail and  OutboundRegistrationDetailComplete events for the response. However, since all events are extended from ManagerEvent, which contains the **Integer line** property, I'm facing the mapping issue, because the OutboundRegistrationDetail event contains line property too, but it's type is string. The ManagerReader reflects the line setter from superclass ManagerEvent, not from mine, and throws the error because the input type is string, not int. The log looks like this:

```
2021-02-24 20:26:54.016 ERROR 7480 --- [tion-0-Reader-0] o.a.manager.internal.EventBuilderImpl    : Unable to set property 'line' to 'true' on com.example.amitest.OutboundRegistrationDetail For input string: "true"

java.lang.NumberFormatException: For input string: "true"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68) ~[na:na]
	at java.base/java.lang.Integer.parseInt(Integer.java:652) ~[na:na]
	at java.base/java.lang.Integer.parseInt(Integer.java:770) ~[na:na]
	at org.asteriskjava.manager.internal.AbstractBuilder.parseInteger(AbstractBuilder.java:150) ~[asterisk-java-3.6.0.jar:na]
	at org.asteriskjava.manager.internal.AbstractBuilder.setAttributes(AbstractBuilder.java:116) ~[asterisk-java-3.6.0.jar:na]
	at org.asteriskjava.manager.internal.EventBuilderImpl.buildEvent(EventBuilderImpl.java:284) ~[asterisk-java-3.6.0.jar:na]
	at org.asteriskjava.manager.internal.ManagerReaderImpl.buildEvent(ManagerReaderImpl.java:363) ~[asterisk-java-3.6.0.jar:na]
	at org.asteriskjava.manager.internal.ManagerReaderImpl.run(ManagerReaderImpl.java:229) ~[asterisk-java-3.6.0.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
```

I don't really need this property, but I don't want the exception to be in my log. Thank you.

**Comment by rlsutton1** [comment]
please try changing ReflectionUtil.getSetters(...) to the following code which will prefer setters from extending classes.

`
public static Map<String, Method> getSetters(Class< ? > clazz)
    {
        final Map<String, Method> accessors = new HashMap<>();
        final Method[] methods = clazz.getMethods();

        for (Method method : methods)
        {

            String name;
            String methodName;

            methodName = method.getName();
            if (!methodName.startsWith("set"))
            {
                continue;
            }

            // skip methods with != 1 parameters
            if (method.getParameterTypes().length != 1)
            {
                continue;
            }

            // OK seems to be an setter
            name = methodName.substring("set".length()).toLowerCase(Locale.US);

            // if an event class implements a setter that exists in
            // ManagerEvent, then prefer the setter from the extending class
            Method existing = accessors.get(name);
            if (existing != null)
            {
                logger.warn("multiple setters (case insensitive) exist for " + name + " on class(es) "
                        + existing.getDeclaringClass() + " and " + method.getDeclaringClass());
            }
            if (existing == null || method.getDeclaringClass().isAssignableFrom(existing.getDeclaringClass()))
            {
                if (existing != null && method.getDeclaringClass().isAssignableFrom(existing.getDeclaringClass()))
                {
                    logger.warn("Preferring setter from extending class " + existing + " -> " + method);
                }
                accessors.put(name, method);
            }
            else
            {
                logger.warn("Preferring setter from extending class " + method + " -> " + existing);
            }

        }

        return accessors;
    }
`


this snippet of code includes logging for diagnostic purposes which should be removed if it works as expected.

Note as the code is case-insensitive - in my quick test with this variant it detected a number of existing duplicate setters where the only difference was the case.

**Comment by 1001v** [comment]
Hello. Thanks for the response. If I understand this right, you suggest me to fork library. This is something I would not like to do. However, I've managed to remove this log by configuring logback.
