### ISSUE TITLE
Missing properties in events

### ISSUE THREAD

**Issue by misterti** [asterisk-java/asterisk-java#372]
I can't find an existing solution to access fields, for example, UniqueId in the PickupEvent. Since built-in PickupEvent is descendant from ManagerEvent, there are many fields, that i need to access, missing.
So far i find that the only solution is to deregister the built-in PickupEvent and register my own version of PickupEvent and adding getters and setters manually.
Is this the intended way to go?

Thanks

**Comment by misterti** [comment]
Anyone?

**Comment by misterti** [comment]
It is actually quite weird that event names are parsed from class names. Wouldn't it be optimal, if parent event class would have event name string property where one could just enter the name of the event and then simply unregister and subclass the original event, add the missing properties and re-register the new event.

**Comment by bsutton** [comment]
The inherent is that you submit pr with the additional fields.

**Comment by misterti** [comment]
Can you explain what you mean by "submit"? and i suppose you meant "pe", not "pr"?

**Comment by bsutton** [comment]
Yes submit a pr.

**Comment by misterti** [comment]
I still don't follow, at all.

**Comment by misterti** [comment]
Ok, so what i managed to scrape out from you vague response is that you are inviting me to submit a "(p)ull (r)equest" where i add missing fields to the repository code?

**Comment by bsutton** [comment]
Correct.

**Comment by piotrooo** [comment]
Currently `PickupEvent` seems to have all of properties.
If you have a specific example - feel free to reopen an issue and attach more details.
