### ISSUE TITLE
DefaultManagerConnection.registerUserEventClass fails with NoClassDefFoundError

### ISSUE THREAD

**Issue by lauberch** [asterisk-java/asterisk-java#381]
registerUserEventClass() fails with the following exception:

> Exception in thread "tims-asterisk-service-196" java.lang.NoClassDefFoundError: Could not initialize class org.asteriskjava.manager.internal.EventBuilderImpl
>         at org.asteriskjava.manager.internal.ManagerReaderImpl.<init>(ManagerReaderImpl.java:112)
>         at org.asteriskjava.manager.internal.ManagerConnectionImpl.createReader(ManagerConnectionImpl.java:272)
>         at org.asteriskjava.manager.internal.ManagerConnectionImpl.registerUserEventClass(ManagerConnectionImpl.java:459)
>         at org.asteriskjava.manager.DefaultManagerConnection.registerUserEventClass(DefaultManagerConnection.java:294)

 This seems caused by an issue in org.regflections

>  Caused by: org.reflections.ReflectionsException: Scanner SubTypesScanner was not configured
>         at org.reflections.Store.get(Store.java:39)
>         at org.reflections.Store.get(Store.java:61)
>         at org.reflections.Store.get(Store.java:46)
>         at org.reflections.Store.getAll(Store.java:93)
>         at org.reflections.Reflections.getSubTypesOf(Reflections.java:404)
>         at org.asteriskjava.manager.internal.EventBuilderImpl.<clinit>(EventBuilderImpl.java:56)
>         ... 10 more

As it turns out this is a known issue in org.reflections 0.9.12. See https://github.com/ronmamo/reflections/issues/273
So I tested with org.reflections  0.10.2 and the issues does not happen then.
Could you please update the dependency accordingly?
Thanks!

[0001-Update-org.reflection-dependency-to-0.10.2.patch.txt](https://github.com/asterisk-java/asterisk-java/files/8013582/0001-Update-org.reflection-dependency-to-0.10.2.patch.txt)

**Comment by rlsutton1** [comment]
I've updated the dependency, a release will follow shortly.

**Comment by lauberch** [comment]
Cool, thanks!  New version seems to be in maven repos already.
