### ISSUE TITLE
Make this project great again

### ISSUE THREAD

**Issue by piotrooo** [asterisk-java/asterisk-java#386]
Is there any possibility to make this project follow current standards?

What I mean?
* fixing release process - following Semver rules
* tracking changes in GitHub Releases
* labeling issues, to help track changes
* running with CI
* handling currently supported Asterisk versions
* maintaining web page asterisk-java.org

I believe with a little of effort we can do it right!

What do you think about it? Ofc I can help with some improvements.

**Comment by piotrooo** [comment]
Yes/No/whatever? Any feedback?

**Comment by bsutton** [comment]
Sorry, I wrote a reply but apparently failed to hit send.

Answer is yes to all.

Currently we lack the resource to help much.

I would be happy to add you as a contributor but to ensure the integrity of the project would you be happy to push a few prs first. 

If everyone is happy with the results we can then add you as a contributor.

**Comment by piotrooo** [comment]
Great!
I'll try to prepare some road map - what and how we should do first.
Ofcourse, some guidance from "old timers" would be really helpful.

**Comment by piotrooo** [comment]
Road map:

- [ ] add GitHub Actions for run tests (CI)
- [ ] review release process, cleanup
- [ ] organize labels in issues/pull request
- [ ] add e.g.: [release-drafter](https://github.com/release-drafter/release-drafter) for changelog automation purposes (based on labels)
- [ ] why project has Maven and Gradle support, should be unified
- [ ] remove old, unused files
- [ ] bump dependencies (e.g.: replacing easymock with mockito - has much more better API)
- [ ] add dependabot
- [ ] add code coverage tool ([codecov](https://about.codecov.io/) and [JaCoCo](https://www.eclemma.org/jacoco/))
- [ ] reconsider code formatting, I suggest to use **default** IntelliJ IDEA, with spaces indentation

For each point should be created appropriate issue.
All issues should be grouped in milestone, can someone create that one?

That could be done as a first phase of making asterisk-java project great again.

**Comment by piotrooo** [comment]
Ping. I need some support on this. Maybe a little bit of discussion is needed here 🙏

**Comment by bsutton** [comment]
What do you need?

**Comment by piotrooo** [comment]
> What do you need?

Some feedback about road map. It's ok? Something should be changed?

**Comment by rlsutton1** [comment]
Hi @piotrooo,

Apologies for the slow response.

I've invited you as a contributor and am intending to make you an administrator once you have accepted the invite.

**Comment by rlsutton1** [comment]
@piotrooo you are now an owner of this repo.

**Comment by piotrooo** [comment]
Closed in favor of #405
