### ISSUE TITLE
Unable to set property 'logintime'

### ISSUE THREAD

**Issue by nasyrovtir** [asterisk-java/asterisk-java#479]
Hello!
We are using the asterisk-java library version 3.29.0

We get the following error:
2023-03-29 14:57:24.910  WARN 7 --- [tion-0-Reader-0] o.a.manager.internal.EventBuilderImpl    : Unable to set property 'logintime' to '1680079168' on org.asteriskjava.manager.event.QueueMemberStatusEvent: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues

UPD: This happened after upgrading Asterisk 16.2.1 -> 16.28.0
UPD2: Updated the the asterisk-java library to version 3.37.0, problem still exists

**Comment by scgm11** [comment]
@piotrooo Hi! can you check why I don't have access to push anymore? Im back in business with this library!

**Comment by piotrooo** [comment]
It's looks like you want to push directly to the master. You need to create a PR with the changes :)

**Comment by scgm11** [comment]
Im pushing to the created branch to make the PR

<img width="1386" alt="Screenshot 2023-04-19 at 09 47 19" src="https://user-images.githubusercontent.com/984668/233079211-54b8add0-44b2-43e2-8eea-6ba4dc7cf830.png">

**Comment by scgm11** [comment]
ok I will try later to see if is my key or something. thanks
