### ISSUE TITLE
QueueMemberPauseEvent missing reasons

### ISSUE THREAD

**Issue by karli1** [asterisk-java/asterisk-java#545]
We have two different Asterisk (20.5.0 and 16.23.0), and use asterisk-java to keep track of the status of our employees. In the old version, we receive the reason in the event (which is pause etc.). In the new version, this is empty, and also pauseReason is empty. We looked with telnet to the AMI (on the new Asterisk), and it is sending this data. So, it seems like we don't get it in the event QueueMemberPauseEvent  set.

**Comment by karli1** [comment]
Meanwhile I could manage a workaround: I created my own QueueMemberPauseEvent with the same serialVersionUID, registered it with registerUserEventClass on the manager connection. The class has the same code like the one from asterisk-java, except I corrected the field/methods for pauseReason to the correct spelling. Now, the pauseReason is filled.

**Comment by seanbright** [comment]
Using `event.getPausedreason()` should give you the information you're after. I will test with the two versions you mentioned and see if I can reproduce it.

**Comment by seanbright** [comment]
I've confirmed with asterisk-java 3.39.0 that you should be using `queueMemberPauseEventObj.getPausedreason()` in both of the versions you mentioned. If you still feel there is a bug please comment and we will re-open.
