### ISSUE TITLE
replace bug/features report address

### ISSUE THREAD

**Issue by videanuadrian** [asterisk-java/asterisk-java#56]
Should we replace all occurences of:

Please report at http://jira.reucon.org/browse/AJ 

with 

Please report at https://github.com/asterisk-java/asterisk-java/issues
?

**Comment by bsutton** [comment]
yes please.

On 04/06/15 19:31, Adrian Videanu wrote:
> Should we replace all occurences of:
> 
> Please report at http://jira.reucon.org/browse/AJ
> 
> with
> 
> Please report at https://github.com/asterisk-java/asterisk-java/issues
> ?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asterisk-java/asterisk-java/issues/56>.
> 


-- 
S. Brett Sutton

Ph: 1300 NOOJEE (1300 666 533)
Noojee Telephony Solutions - On Demand Contact Centres Solutions
www.noojee.com.au
