### ISSUE TITLE
Missing Example for Dial

### ISSUE THREAD

**Issue by sytolk** [asterisk-java/asterisk-java#61]
I have connection to Manager API on my local Asterisk service and I have registered SIP users in sip.conf and numbers for this users in extensions.conf and I want to make a call using asterisk-java lib. SIP user is logged in Zoiper. But I cant find example for this. Can I make a SIP call with this library? If yes it will be useful to add this code in READMI.md examples.

**Comment by sytolk** [comment]
I have write this code its work but I have Warnings for missing setter in log:
```
16:11:09,411  INFO ManagerConnectionImpl:94 - Connecting to localhost:5038
16:11:09,541  INFO ManagerConnectionImpl:94 - Connected via Asterisk Call Manager/2.7.0
16:11:09,568  INFO ManagerConnectionImpl:94 - Successfully logged in
16:11:09,572  INFO ManagerConnectionImpl:94 - Determined Asterisk version: Asterisk 13
Success
16:11:13,954  WARN EventBuilderImpl:110 - Unable to set property 'statustext' to 'Ringing' on org.asteriskjava.manager.event.ExtensionStatusEvent: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
16:11:13,960  WARN EventBuilderImpl:110 - Unable to set property 'statustext' to 'InUse' on org.asteriskjava.manager.event.ExtensionStatusEvent: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
16:11:13,964  WARN EventBuilderImpl:110 - Unable to set property 'statustext' to 'Ringing' on org.asteriskjava.manager.event.ExtensionStatusEvent: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
16:11:13,976  INFO ManagerConnectionImpl:94 - Closing socket.
16:11:13,976  INFO ManagerReaderImpl:94 - Terminating reader thread: No more lines available: null
```

```java
import org.asteriskjava.manager.AuthenticationFailedException;
import org.asteriskjava.manager.ManagerConnection;
import org.asteriskjava.manager.ManagerConnectionFactory;
import org.asteriskjava.manager.TimeoutException;
import org.asteriskjava.manager.action.OriginateAction;
import org.asteriskjava.manager.response.ManagerResponse;

import java.io.IOException;

/**
 * Created with IntelliJ IDEA.
 * User: stanimir
 * Date: 6/18/15
 * Time: 3:54 PM
 * developer STANIMIR MARINOV
 */
public class Dial {
        private ManagerConnection managerConnection;

        public Dial() throws IOException {
            ManagerConnectionFactory factory = new ManagerConnectionFactory("localhost", "admin", "XXXXXX");

            this.managerConnection = factory.createManagerConnection();
        }

        public void call() throws IOException, AuthenticationFailedException, TimeoutException {
            OriginateAction originateAction;
            ManagerResponse originateResponse;
            originateAction = new OriginateAction();
            originateAction.setChannel("SIP/6000"); //from user
            originateAction.setContext("default");
            originateAction.setExten("6001");
            originateAction.setPriority(new Integer(1));
            originateAction.setTimeout(new Integer(30000));
            // connect to Asterisk and log in
            managerConnection.login();
            // send the originate action and wait for a maximum of 30 seconds for Asterisk to send a reply
            originateResponse = managerConnection.sendAction(originateAction, 30000);
            // print out whether the originate succeeded or not
            System.out.println(originateResponse.getResponse());
            // and finally log off and disconnect
            managerConnection.logoff();
        }

        public static void main(String[] args) throws Exception {
            Dial dialManager = new Dial();
            dialManager.call();
        }
}
```

**Comment by sytolk** [comment]
Dial work but users need to have softphone. Can I use only this library to make softphone?

**Comment by michaelrice** [comment]
@sytolk there are TONS of free softphones out there if you dont want to make your own.. If you wanted to make your own I would look into jsip https://jsip.java.net/

**Comment by sytolk** [comment]
SIP have problems with NAT and internet providers. @michaelrice Do you know open source java IAX2 working softphone ?

**Comment by michaelrice** [comment]
@sytolk I dont off the top of my head. You might take a look at this: http://www.voip-info.org/wiki/view/Asterisk+IAX+clients

**Comment by relrix** [comment]
Here is a java version of iaxclient (http://sourceforge.net/projects/iaxclient/) written in Java by Mikael Magnusson. 
http://www.shishir.com.np/home/2011/11/28/jiaxclient-using-iaxclient-java-version-of-iaxclient/

**Comment by bsutton** [comment]
Generally speaking 'every' softphone out there is rubbish and you should really go for a desk phone like the yealink (which has a really nice vpn client builtin). 

But if you really want to go softphone then counterpaths xlite or bria are the best options in a softphone.

http://www.counterpath.com/x-lite/

xlite is free. The bria is about $USD50 and has a couple of extra features the key one being g729 (compression).

**Comment by sytolk** [comment]
I wonder why there is so little open source software written for IAX2 softphone (native Java is missing) ?? IAX2 is protocol only its have only C++ for Microsoft Visual Studio-discontinued projects like this:
http://sourceforge.net/projects/iaxclient/  @relrix this is not Java

**Comment by srt** [comment]
@sytolk did you have a look at https://github.com/asterisk-java/asterisk-java-iax it is a pure Java implementation of IAX2 though it is not activley maintained at the moment.

**Comment by sytolk** [comment]
maybe not thanks @srt

**Comment by waynemerricks** [comment]
Hi,

I don't know if this will help, I use BareSIP (linux command line) as a backend for radio studios outputting via a balanced audio card.  It can be controlled via a web interface/API.  This way you could make a "pretty" Java front end.

I use this: https://github.com/waynemerricks/asteriskphone

It works with any SIP client as long as they have an auto-answer facility or respect the auto answer SIP headers sent by Asterisk (most Desk Phones do, soft phones generally don't).

**Comment by sytolk** [comment]
sounds interesting thanks @waynemerricks

**Comment by seanbright** [comment]
I've read the comments on this issue a few times and I am not able to see a bug in asterisk-java, so I am closing.
