### ISSUE TITLE
Project maintenance request

### ISSUE THREAD

**Issue by seanbright** [asterisk-java/asterisk-java#610]
Hi 👋🏼 

I’d like to volunteer to take over project maintenance. Please let me know what information you need from me.

**Comment by seanbright** [comment]
I moved this to a discussion but to increase visibility I’m going to reopen this.

**Comment by scgm11** [comment]
these are the current mainteiners Im as a contributor so I cannot add you

<img width="467" alt="Screenshot 2024-08-26 at 1 58 52 PM" src="https://github.com/user-attachments/assets/ee3a5f69-543b-47a3-8a8b-dc4e721e9e76">


@piotrooo @srt @bsutton ?

**Comment by srt** [comment]
Hey, thanks for pining me. Though I founded this project I moved on quite some time ago so I am not up to date with the current status of the team.
What does the current team think?

**Comment by seanbright** [comment]
For what it's worth I am a frequent [contributor to Asterisk](https://github.com/asterisk/asterisk/commits?author=seanbright) and previously contributed to [this project](https://github.com/asterisk-java/asterisk-java/commits?author=seanbright) as well.

**Comment by bsutton** [comment]
I've seen enough of Sean's work that I'm happy to add him as an owner.

If there are no objections, I will do this tomorrow.

**Comment by piotrooo** [comment]
I invited a @seanbright as an owner. Maybe with a couple of members, I'll also try to come back to actively supporting this project.

> I'm also open to the idea of someone else maintaining this project if that is the consensus.

I had some ideas about it and a general plan, but due to a lack of time and being alone in this project, I stopped to contributing :sob:.

**Comment by bsutton** [comment]
ok, so if you have invited sean, sounds like there is nothing left for me
to do.

Feel free to remove me as a project owner.

Good Luck.

**Comment by seanbright** [comment]
Thank you @piotrooo!

Thanks for all you’ve done @bsutton. I appreciate the vote of confidence.

**Comment by srt** [comment]
Thanks for moving this project forward @seanbright !
Let me know if there is anything I can do to help out.

**Comment by seanbright** [comment]
@srt it looks like @piotrooo added me in the "Owners" team but did not give me ownership permissions to [the organization](https://github.com/orgs/asterisk-java/people).

The process that is currently releasing to maven central is failing due to an authentication issue and it is not something I am able to debug without the necessary permissions - I'm not even sure if getting added with ownership permissions would give me access to [the information I think I need](https://github.com/asterisk-java/asterisk-java/settings/secrets/actions) but it certainly can't hurt.

I'm happy to sign something saying I will not do evil or whatever is necessary to move this forward.

**Comment by seanbright** [comment]
Hello @srt @bsutton @rlsutton1 @piotrooo,

I apologize for pinging all of you but I am unable to move forward. I need the Nexus username & password so that I can update our deployment process to use [token authentication](https://community.sonatype.com/t/401-content-access-is-protected-by-token-authentication-failure-while-performing-maven-release/12741/3).

I believe that making me an [owner of the asterisk-java organization](https://github.com/orgs/asterisk-java/people) would allow me to see the "secrets" that are currently stored for use by the CI, and will also allow me to not have to bother any of you with this sort of request going forward.

I would greatly appreciate if one of you could help me move this forward.

Thank you,
Sean

**Comment by seanbright** [comment]
This is resolved
