### ISSUE TITLE
org.asteriskjava.manager.internal.EventBuilderImpl - Unable to set property...no setter

### ISSUE THREAD

**Issue by speedy01** [asterisk-java/asterisk-java#66]
using 2.0 snapshot
org.asteriskjava.manager.internal.EventBuilderImpl - Unable to set property.....

'eventlist' to'Complete' on org.asteriskjava.manager.event.QueueStatusCompleteEvent: no setter. 
'listitems' to'1' on org.asteriskjava.manager.event.QueueStatusCompleteEvent: no setter. 
'eventlist' to'Complete' on org.asteriskjava.manager.event.StatusCompleteEvent: no setter. 
'listitems' to'0' on org.asteriskjava.manager.event.StatusCompleteEvent: no setter. 
'eventlist' to'Complete' on org.asteriskjava.manager.event.QueueStatusCompleteEvent: no setter. 
'listitems' to'1' on org.asteriskjava.manager.event.QueueStatusCompleteEvent: no setter. 
'language' to'en' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'report0sourcessrc' to'0x21337ddc' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'report0dlsr' to'2.0960' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'sentntp' to'3522090500.17560498606080' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'sentpackets' to'604' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'sentrtp' to'96800' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'uniqueid' to'1436111389.0' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'reportcount' to'1' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'report0cumulativelost' to'0' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'report0sequencenumbercycles' to'0' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'ssrc' to'0x35552983' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'report0highestsequence' to'50896' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'report0fractionlost' to'0' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'sentoctets' to'96800' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'report0iajitter' to'49' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'to' to'[::1]:0' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'report0lsr' to'3500631455' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'channel' to'SIP/2001-00000000' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'language' to'en' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'report0sourcessrc' to'0x21337ddc' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'report0dlsr' to'4.8920' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'sentntp' to'3522090503.17560498606080' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'sentpackets' to'744' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'sentrtp' to'119200' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'uniqueid' to'1436111389.0' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'reportcount' to'1' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'report0cumulativelost' to'0' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'report0sequencenumbercycles' to'0' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. 
'ssrc' to'0x35552983' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter.

**Comment by bsutton** [comment]
Speedy, would you be able to add the setters and submit a pull request?

**Comment by speedy01** [comment]
bsutton,
I wish I knew how, as I'm not a dev, just an intergrator/generalist.  Can you provide me with some examples on the "how" and I'll be happy to give it a try.

**Comment by bsutton** [comment]
closing as resolved as part of #112 fixes.
