### ISSUE TITLE
Dataobject question

### ISSUE THREAD

**Issue by michaelrice** [asterisk-java/asterisk-java#68]
Hello,

Would you be open to using something like [Project Lombok](https://projectlombok.org/download.html) in the dataobjects to cut down on the getters and setters? For example #67 is hundreds of lines of boiler plate code. Project lombok could cut that down to under 100 lines.. Just thought Id ask before I did any work on it..

**Comment by bsutton** [comment]
appologies for the late response.

My inclination is no.

Whilst I also hate the boiler plate code I'm not a big fan of having to
inject the lombok jar into the compile path.

We use something similar for jpa here (as well as having toyed with
lombok previously) and our experience is that the tooling tends to get
in the way.

But what do other people think about Lombok?

Brett


On 07/07/15 19:07, Michael Rice wrote:
> Hello,
> 
> Would you be open to using something like Project Lombok
> <https://projectlombok.org/download.html> in the dataobjects to cut down
> on the getters and setters? For example #67
> <https://github.com/asterisk-java/asterisk-java/pull/67> is hundreds of
> lines of boiler plate code. Project lombok could cut that down to under
> 100 lines.. Just thought Id ask before I did any work on it..
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asterisk-java/asterisk-java/issues/68>.
> 


-- 
S. Brett Sutton

Ph: 1300 NOOJEE (1300 666 533)
Noojee Telephony Solutions - On Demand Contact Centres Solutions
www.noojee.com.au

**Comment by bsutton** [comment]
Will close as I've not had any ground swell of support for the idea.
