### ISSUE TITLE
AsteriskLive ChannelManager does not record any channels

### ISSUE THREAD

**Issue by pk1057** [asterisk-java/asterisk-java#72]
It seems that the channel manager are not initialized correctly in current git, so any query to asterisk server getChannels leads to an empty list.

In commit 0ab2997 the initializing in intializeIfNeeded is removed.

When i reImplement this code section, the channel manager works nearly as expected, channels where populated in ChannelManager but not linkedChannels

**Comment by bsutton** [comment]
sorry for the late response.

I think you have linked to the wrong commit. Can you the details of the code change you made and the correct commit.

ta,
brett

**Comment by pk1057** [comment]
Sorry in this commit the Channel manager was removed and until this commit i get no calls in the channel manager populated

https://github.com/asterisk-java/asterisk-java/commit/a424ca7f904446bb2e9cf641ad8f9aaf787a3bc0#diff-bc1b8e12e7c3d17c6d78149bd0b79b14

**Comment by bsutton** [comment]
there has been significant changes to this code area so I'm going to reject this commit.
