### ISSUE TITLE
Unable to set property StatusCompleteEvent

### ISSUE THREAD

**Issue by AlineaSol** [asterisk-java/asterisk-java#78]
Hello,

We are using:
- Asterisk 13.5.0
- Asterisk Call Manager/2.8.0 (1)
- Asterisk java 2.0.0.CI-SNAPSHOT

And while the connetion is being stablished this warn is logged:
 WARN  Unable to set property 'eventlist' to 'Complete' on org.asteriskjava.manager.event.StatusCompleteEvent: no setter...

Please could you tell us what it means?

(1) We know that this version is not already supported but the new features don't affect to our app.

**Comment by bsutton** [comment]
as the message says its missing a setter. This isn't critical unless you 
need to access the value of eventlist.

You can fix the issue by adding a setter to the StatusCompleteEvent class.

**Comment by bsutton** [comment]
This was fixed along with #112 so I'm closing.
