### ISSUE TITLE
Asterisk-java in @Singleton EJB

### ISSUE THREAD

**Issue by elettrico** [asterisk-java/asterisk-java#97]
Hi, I'm using asterisk-java version 1.1 beta in a enterprise environment (glassfish 4.0).
I've a singleton bean managing connections and events. It works fine but sometimes it seems that something "go mad" and then it starts rejecting executions:

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7b485252 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@6c53f5a7[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at org.asteriskjava.live.internal.ChannelManager.addNewChannel(ChannelManager.java:234)
	at org.asteriskjava.live.internal.ChannelManager.handleNewChannelEvent(ChannelManager.java:485)
	at org.asteriskjava.live.internal.AsteriskServerImpl.onManagerEvent(AsteriskServerImpl.java:1015)
	at org.asteriskjava.manager.ManagerEventListenerProxy$1.run(ManagerEventListenerProxy.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)]]

It is safe to run asterisk-java inside an EJB container?

**Comment by bsutton** [comment]
My best guess is that you are getting disconnected from asterisk and the 
threadpool is being shutdown on the back of the disconnect.

This can happen if you are not processing asterisk events fast enough.

I can see a scenario where you have a backlog of events, asterisk 
disconnects you and the channel manager trys to process the backlog and 
you get the below exception.

So have a close look at the code that is handling events could you be 
doing something to be slowing down the handling of events such as a long 
db call?

Brett

**Comment by elettrico** [comment]
I'm programming a panel, so basically I'm storing data in some hashmap and lists and sending jms messages to the war frontend, apparently nothing slow. I'll check the status of the asterisk connection every 5 secs and it's always true. I suspect there's a sort of incompatibility between the singleton ejb and the asteriskserver live: it stops sendings events to the singleton after the first exception (exceptions are always in thread "AJ DaemonPool-N.NNNN") and I cannot access the asteriskserver anymore (asteriskserver.shutdown() does nothing), the only way to get all working is restarting glassfish.
I'm stuck, do you know if exists a working example of asteriskserver live in an EJB environment?

**Comment by bsutton** [comment]
I've never tried asterisk-java an an ejb but I'm reluctant to believe 
that the ejb is causing the problem.

I've pushed a small patch to asterisk-java 1.1 which logs disconnects in 
the ChannelManager.

Grab the patch and lets see if its getting a disconnect.

Brett

**Comment by elettrico** [comment]
Ok, I was talking about ejb because thread management is somewhat different inside an ejb container.
I'll grab the patch and see, meanwhile I've deployed the same app to glasshfish 4.1 and I'm seeing slightly differences, for example I get two messages on shutdown ("Terminating reader thread: No more lines available: null" and "Closing socket") that doesn't appear in glassfish 4.0.
I plan to stress test it tomorrow and see what happen.

**Comment by bsutton** [comment]
Whilst the ejb container will play with threads I would be surprised if 
it goes around terminating threads that you manually start as opposed to 
the thread pools it manages.

As to the different messages you are seeing, not enough information to 
give you a meaningful response.

**Comment by elettrico** [comment]
Until now I've no issues with glassfish 4.1.
I'll wait until a big peak and if everything works fine I'll close this issue.
